<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Exercise</title>

<script src="site_libs/header-attrs-2.29/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/readable.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/navigation-1.1/codefolding.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<link href="site_libs/font-awesome-6.5.2/css/all.min.css" rel="stylesheet" />
<link href="site_libs/font-awesome-6.5.2/css/v4-shims.min.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->
<style type="text/css">
.code-folding-btn { margin-bottom: 4px; }
</style>




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html"></a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">
    <span class="fa fa-solid fa-spa"></span>
     
  </a>
</li>
<li>
  <a href="report.html">Report</a>
</li>
<li>
  <a href="data.html">Data</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Lifestyle Factors Analyses
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="hormone_symtoms_final.html">Hormone &amp; Symptoms</a>
    </li>
    <li>
      <a href="sleep_stress_final.html">Sleep &amp; Stress</a>
    </li>
    <li>
      <a href="exercise_final.html">Exercise</a>
    </li>
  </ul>
</li>
<li>
  <a href="p8105_final_project_proposal.html">Proposal</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="https://github.com/liisnotlee/p8105_final_project.github.io">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">

<div class="btn-group pull-right float-right">
<button type="button" class="btn btn-default btn-xs btn-secondary btn-sm dropdown-toggle" data-toggle="dropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
<ul class="dropdown-menu dropdown-menu-right" style="min-width: 50px;">
<li><a id="rmd-show-all-code" href="#">Show All Code</a></li>
<li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li>
</ul>
</div>



<h1 class="title toc-ignore">Exercise</h1>

</div>


<p>The following exploratory analysis investigates the relationship
between objectively measured exercise (steps, active minutes, calories)
metrics and self-reported menstrual symptoms across different menstrual
cycle phases. We use data from both study intervals (2022 and 2024) to
examine whether physical activity is associated with symptom
severity.</p>
<div id="data-summary" class="section level3">
<h3>Data Summary</h3>
<div id="data-quality-check" class="section level4">
<h4>Data Quality Check</h4>
<p>Five observations showed extreme step counts (≥50,000) likely due to
device errors. These were excluded from step count visualizations only,
all analyses use the complete dataset as extreme values were isolated to
step counts.These observations are retained in all descriptive
statistics and statistical models to preserve the complete dataset. They
are excluded only from the step count distribution plot to prevent
visual distortion.</p>
<pre class="r"><code># Outlier check: Identifying and viewing extreme observations
extreme_obs = read.csv(&quot;./clean_data/all_daily_data.csv&quot;) |&gt; 
  distinct(id, study_interval, day_in_study, .keep_all = TRUE) |&gt; 
  filter(total_steps &gt;= 50000 | # unlikely to complete more than 50000 steps a day
         total_active_min &gt;= 1440 | # cannot have active exercise minutes for more than 24 hours
         total_calories &gt;= 10000) |&gt; # unlikely to burn more than 10000 calories in a day
  select(id, study_interval, day_in_study, 
         total_steps, total_active_min, total_calories) |&gt; 
  arrange(desc(total_steps))

# Displaying extreme observations
  kable(extreme_obs,
        caption = &quot;Outliers with Extreme Values&quot;,
        col.names = c(&quot;ID&quot;, &quot;Year&quot;, &quot;Day&quot;, &quot;Steps&quot;, &quot;Active Min&quot;, 
                     &quot;Calories&quot;)) |&gt; 
  kable_styling(bootstrap_options = c(&quot;striped&quot;, &quot;hover&quot;))</code></pre>
<table class="table table-striped table-hover" style="margin-left: auto; margin-right: auto;">
<caption>
Outliers with Extreme Values
</caption>
<thead>
<tr>
<th style="text-align:right;">
ID
</th>
<th style="text-align:right;">
Year
</th>
<th style="text-align:right;">
Day
</th>
<th style="text-align:right;">
Steps
</th>
<th style="text-align:right;">
Active Min
</th>
<th style="text-align:right;">
Calories
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
22
</td>
<td style="text-align:right;">
2024
</td>
<td style="text-align:right;">
883
</td>
<td style="text-align:right;">
1880842
</td>
<td style="text-align:right;">
273.4644
</td>
<td style="text-align:right;">
183
</td>
</tr>
<tr>
<td style="text-align:right;">
14
</td>
<td style="text-align:right;">
2024
</td>
<td style="text-align:right;">
922
</td>
<td style="text-align:right;">
1877616
</td>
<td style="text-align:right;">
234.2144
</td>
<td style="text-align:right;">
129
</td>
</tr>
<tr>
<td style="text-align:right;">
18
</td>
<td style="text-align:right;">
2024
</td>
<td style="text-align:right;">
922
</td>
<td style="text-align:right;">
1877616
</td>
<td style="text-align:right;">
253.8477
</td>
<td style="text-align:right;">
238
</td>
</tr>
<tr>
<td style="text-align:right;">
27
</td>
<td style="text-align:right;">
2024
</td>
<td style="text-align:right;">
887
</td>
<td style="text-align:right;">
1877616
</td>
<td style="text-align:right;">
234.2144
</td>
<td style="text-align:right;">
129
</td>
</tr>
<tr>
<td style="text-align:right;">
33
</td>
<td style="text-align:right;">
2024
</td>
<td style="text-align:right;">
887
</td>
<td style="text-align:right;">
1877616
</td>
<td style="text-align:right;">
234.2144
</td>
<td style="text-align:right;">
129
</td>
</tr>
</tbody>
</table>
</div>
<div id="descriptives-exercise-metrics" class="section level4">
<h4>Descriptives: Exercise Metrics</h4>
<pre class="r"><code># Loading data
all_daily_data = read.csv(&quot;./clean_data/all_daily_data.csv&quot;) |&gt; 
  distinct(id, study_interval, day_in_study, .keep_all = TRUE)

# Exercise descriptives
overall_desc = all_daily_data |&gt; 
  summarise(
    Variable = c(&quot;Daily Steps&quot;, &quot;Active Minutes/Day&quot;, &quot;Calories Burned&quot;, 
                 &quot;Exercise Sessions/Day&quot;, &quot;Days with Activity (%)&quot;),
    Mean = round(c(mean(total_steps, na.rm = TRUE),
                   mean(total_active_min, na.rm = TRUE),
                   mean(total_calories, na.rm = TRUE),
                   mean(n_sessions, na.rm = TRUE),
                   NA), 2),
    SD = round(c(sd(total_steps, na.rm = TRUE),
                 sd(total_active_min, na.rm = TRUE),
                 sd(total_calories, na.rm = TRUE),
                 sd(n_sessions, na.rm = TRUE),
                 NA), 2),
    Median = round(c(median(total_steps, na.rm = TRUE),
                     median(total_active_min, na.rm = TRUE),
                     median(total_calories, na.rm = TRUE),
                     median(n_sessions, na.rm = TRUE),
                     NA), 2),
    IQR = round(c(IQR(total_steps, na.rm = TRUE),
                  IQR(total_active_min, na.rm = TRUE),
                  IQR(total_calories, na.rm = TRUE),
                  IQR(n_sessions, na.rm = TRUE),
                  NA), 2),
    Percent = round(c(NA, NA, NA, NA,
                      mean(exercised_flag &gt; 0, na.rm = TRUE) * 100), 2)
  )

# Displaying table (and making NAs blank)
overall_desc |&gt; 
  mutate(across(where(is.numeric), ~ifelse(is.na(.), &quot;&quot;, .))) |&gt; 
  kable(caption = &quot;Descriptive Statistics: Exercise Metrics&quot;,
        align = c(&quot;l&quot;, &quot;r&quot;, &quot;r&quot;, &quot;r&quot;, &quot;r&quot;, &quot;r&quot;)) %&gt;%
  kable_styling(bootstrap_options = c(&quot;striped&quot;, &quot;hover&quot;), full_width = FALSE)</code></pre>
<table class="table table-striped table-hover" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
Descriptive Statistics: Exercise Metrics
</caption>
<thead>
<tr>
<th style="text-align:left;">
Variable
</th>
<th style="text-align:right;">
Mean
</th>
<th style="text-align:right;">
SD
</th>
<th style="text-align:right;">
Median
</th>
<th style="text-align:right;">
IQR
</th>
<th style="text-align:right;">
Percent
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Daily Steps
</td>
<td style="text-align:right;">
10673.14
</td>
<td style="text-align:right;">
100251.66
</td>
<td style="text-align:right;">
4370
</td>
<td style="text-align:right;">
5088.25
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:left;">
Active Minutes/Day
</td>
<td style="text-align:right;">
65.7
</td>
<td style="text-align:right;">
50.43
</td>
<td style="text-align:right;">
52.05
</td>
<td style="text-align:right;">
59.73
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:left;">
Calories Burned
</td>
<td style="text-align:right;">
226.74
</td>
<td style="text-align:right;">
225.59
</td>
<td style="text-align:right;">
153
</td>
<td style="text-align:right;">
209
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:left;">
Exercise Sessions/Day
</td>
<td style="text-align:right;">
2.09
</td>
<td style="text-align:right;">
1.31
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:left;">
Days with Activity (%)
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
30.82
</td>
</tr>
</tbody>
</table>
<p>Overall, participants demonstrated moderate daily physical activity
levels. The median daily step count was 4,370 steps, with a mean of
10,673.14 steps (SD = 100,251.7). The large standard deviation and
difference between mean and median indicate presence of extreme outlier
observations (as identified earlier). Active exercise time averaged 65.7
minutes per day (Median = 52.05 minutes), with participants burning an
average of 226.74 calories per session (Median = 153). Most participants
engaged in 2.09 exercise sessions per day (Median = 2). Physical
activity was recorded on 30.82% of study days, indicating high
compliance with activity tracking.</p>
<pre class="r"><code># Comparison by study year
year_comp = all_daily_data |&gt; 
  group_by(study_interval) |&gt; 
  summarise(
    `N Days` = n(),
    `N Participants` = n_distinct(id),
    `Mean Steps` = round(mean(total_steps, na.rm = TRUE), 2),
    `SD Steps` = round(sd(total_steps, na.rm = TRUE), 2),
    `Mean Active Min` = round(mean(total_active_min, na.rm = TRUE), 2),
    `SD Active Min` = round(sd(total_active_min, na.rm = TRUE), 2),
    `% Days Active` = round(mean(exercised_flag, na.rm = TRUE) * 100, 2)
  ) |&gt; 
  rename(Year = study_interval)

kable(year_comp,
      caption = &quot;Exercise Metrics by Study Year&quot;,
      align = c(&quot;c&quot;, rep(&quot;r&quot;, 7))) %&gt;%
  kable_styling(bootstrap_options = c(&quot;striped&quot;, &quot;hover&quot;), full_width = FALSE)</code></pre>
<table class="table table-striped table-hover" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
Exercise Metrics by Study Year
</caption>
<thead>
<tr>
<th style="text-align:center;">
Year
</th>
<th style="text-align:right;">
N Days
</th>
<th style="text-align:right;">
N Participants
</th>
<th style="text-align:right;">
Mean Steps
</th>
<th style="text-align:right;">
SD Steps
</th>
<th style="text-align:right;">
Mean Active Min
</th>
<th style="text-align:right;">
SD Active Min
</th>
<th style="text-align:right;">
% Days Active
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
2022
</td>
<td style="text-align:right;">
3698
</td>
<td style="text-align:right;">
42
</td>
<td style="text-align:right;">
3991.31
</td>
<td style="text-align:right;">
3132.28
</td>
<td style="text-align:right;">
47.79
</td>
<td style="text-align:right;">
37.63
</td>
<td style="text-align:right;">
14.6
</td>
</tr>
<tr>
<td style="text-align:center;">
2024
</td>
<td style="text-align:right;">
1961
</td>
<td style="text-align:right;">
20
</td>
<td style="text-align:right;">
13669.97
</td>
<td style="text-align:right;">
120533.68
</td>
<td style="text-align:right;">
73.73
</td>
<td style="text-align:right;">
53.30
</td>
<td style="text-align:right;">
61.4
</td>
</tr>
</tbody>
</table>
<p>Exercise patterns differed substantially between study years. The
2024 cohort showed considerably higher activity levels compared to 2022
across all metrics. 2024 participants averaged 73.73 active minutes per
day compared to 47.79 minutes in 2022. The proportion of days with
recorded activity increased from 14.6% in 2022 to 61.4% in 2024.</p>
</div>
<div id="descriptives-symptom-severity" class="section level4">
<h4>Descriptives: Symptom Severity</h4>
<pre class="r"><code># Symptom descriptives
symptom_desc = all_daily_data |&gt; 
  summarise(
    across(c(appetite_score, headaches_score, cramps_score, sorebreasts_score, fatigue_score, sleepissue_score, moodswing_score, foodcravings_score, indigestion_score, bloating_score),
           list(mean = ~mean(.x, na.rm = TRUE),
                sd = ~sd(.x, na.rm = TRUE),
                median = ~median(.x, na.rm = TRUE)),
           .names = &quot;{.col}_{.fn}&quot;)
  ) |&gt; 
  pivot_longer(everything(),
               names_to = c(&quot;symptom&quot;, &quot;.value&quot;),
               names_pattern = &quot;(.+)_score_(.+)&quot;) |&gt; 
  mutate(
    symptom = str_to_title(str_replace_all(symptom, &quot;_&quot;, &quot; &quot;)),
    across(where(is.numeric), ~round(.x, 2))
  ) |&gt; 
  # Alphabetical order
  arrange(symptom)

kable(symptom_desc,
      col.names = c(&quot;Symptom&quot;, &quot;Mean&quot;, &quot;SD&quot;, &quot;Median&quot;),
      caption = &quot;Symptom Severity (Scale: 0 = None, 5 = Very High)&quot;,
      align = c(&quot;l&quot;, &quot;r&quot;, &quot;r&quot;, &quot;r&quot;)) %&gt;%
  kable_styling(bootstrap_options = c(&quot;striped&quot;, &quot;hover&quot;), full_width = FALSE)</code></pre>
<table class="table table-striped table-hover" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
Symptom Severity (Scale: 0 = None, 5 = Very High)
</caption>
<thead>
<tr>
<th style="text-align:left;">
Symptom
</th>
<th style="text-align:right;">
Mean
</th>
<th style="text-align:right;">
SD
</th>
<th style="text-align:right;">
Median
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Appetite
</td>
<td style="text-align:right;">
2.91
</td>
<td style="text-align:right;">
0.83
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
Bloating
</td>
<td style="text-align:right;">
1.60
</td>
<td style="text-align:right;">
1.48
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
Cramps
</td>
<td style="text-align:right;">
1.00
</td>
<td style="text-align:right;">
1.27
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
Fatigue
</td>
<td style="text-align:right;">
2.50
</td>
<td style="text-align:right;">
1.48
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
Foodcravings
</td>
<td style="text-align:right;">
1.83
</td>
<td style="text-align:right;">
1.53
</td>
<td style="text-align:right;">
2
</td>
</tr>
<tr>
<td style="text-align:left;">
Headaches
</td>
<td style="text-align:right;">
1.46
</td>
<td style="text-align:right;">
1.41
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
Indigestion
</td>
<td style="text-align:right;">
1.45
</td>
<td style="text-align:right;">
1.42
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
Moodswing
</td>
<td style="text-align:right;">
1.57
</td>
<td style="text-align:right;">
1.42
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
Sleepissue
</td>
<td style="text-align:right;">
2.01
</td>
<td style="text-align:right;">
1.48
</td>
<td style="text-align:right;">
2
</td>
</tr>
<tr>
<td style="text-align:left;">
Sorebreasts
</td>
<td style="text-align:right;">
0.85
</td>
<td style="text-align:right;">
1.11
</td>
<td style="text-align:right;">
0
</td>
</tr>
</tbody>
</table>
<p>Symptom severity varied across menstrual cycle phases and between
individuals. Most physical symptoms showed low-to-moderate mean severity
on the 0-5 scale: cramps (M = 1, SD = 1.27), fatigue (M = 2.5, SD =
1.48), and bloating (M = 1.6, SD = 1.48). Psychological symptoms
including mood swings (M = 1.57, SD = 1.42) and appetite changes (M =
2.91, SD = 0.83) were similarly mild to moderate on average. The
relatively large standard deviations across all symptoms reflect
substantial variability in symptom experiences across the menstrual
cycle.</p>
</div>
</div>
<div id="distribution-of-key-exercise-metrics" class="section level3">
<h3>Distribution of Key Exercise Metrics</h3>
<pre class="r"><code>exercise_analysis = all_daily_data

# Distribution of daily step count
p1 = ggplot(exercise_analysis |&gt; filter(total_steps &gt; 0, total_steps &lt; 50000), 
             aes(x = total_steps, fill = factor(study_interval))) +
  geom_histogram(bins = 50, alpha = 0.7, position = &quot;dodge&quot;) +
  geom_vline(xintercept = median(exercise_analysis$total_steps[exercise_analysis$total_steps &gt; 0], na.rm = TRUE),
             linetype = &quot;dashed&quot;, color = &quot;black&quot;, linewidth = 1) +
  labs(title = &quot;Daily Step Count Distribution&quot;,
       subtitle = paste(&quot;Median:&quot;, 
                       scales::comma(round(median(exercise_analysis$total_steps[exercise_analysis$total_steps &gt; 0], na.rm = TRUE))), 
                       &quot;steps&quot;),
       x = &quot;Total Daily Steps&quot;,
       y = &quot;Count&quot;,
       fill = &quot;Study Year&quot;) +
  scale_x_continuous(labels = scales::comma)

# Active minutes distribution
p2 = ggplot(exercise_analysis |&gt; filter(total_active_min &gt; 0), 
             aes(x = total_active_min, fill = factor(study_interval))) +
  geom_histogram(bins = 50, alpha = 0.7, position = &quot;dodge&quot;) +
  geom_vline(xintercept = median(exercise_analysis$total_active_min[exercise_analysis$total_active_min &gt; 0], na.rm = TRUE),
             linetype = &quot;dashed&quot;, color = &quot;black&quot;, linewidth = 1) +
  labs(title = &quot;Active Minutes Distribution&quot;,
       subtitle = paste(&quot;Median:&quot;, 
                       round(median(exercise_analysis$total_active_min[exercise_analysis$total_active_min &gt; 0], na.rm = TRUE), 1), 
                       &quot;minutes&quot;),
       x = &quot;Total Active Minutes&quot;,
       y = &quot;Count&quot;,
       fill = &quot;Study Year&quot;)

# Calories Burned Distribution
p3 = ggplot(exercise_analysis |&gt; filter(total_calories &gt; 0), 
             aes(x = total_calories, fill = factor(study_interval))) +
  geom_histogram(bins = 50, alpha = 0.7, position = &quot;dodge&quot;) +
  geom_vline(xintercept = median(exercise_analysis$total_calories[exercise_analysis$total_calories &gt; 0], na.rm = TRUE),
             linetype = &quot;dashed&quot;, color = &quot;black&quot;, linewidth = 1) +
  labs(title = &quot;Calories Burned Distribution&quot;,
       subtitle = paste(&quot;Median:&quot;, 
                       scales::comma(round(median(exercise_analysis$total_calories[exercise_analysis$total_calories &gt; 0], na.rm = TRUE))), 
                       &quot;calories&quot;),
       x = &quot;Total Calories Burned&quot;,
       y = &quot;Count&quot;,
       fill = &quot;Study Year&quot;) +
  scale_x_continuous(labels = scales::comma)

# Exercise Sessions Per Day
p4 = ggplot(exercise_analysis |&gt; filter(n_sessions &gt; 0), 
             aes(x = n_sessions, fill = factor(study_interval))) +
  geom_bar(alpha = 0.7, position = &quot;dodge&quot;) +
  labs(title = &quot;Exercise Sessions Per Day&quot;,
       x = &quot;Number of Sessions&quot;,
       y = &quot;Count&quot;,
       fill = &quot;Study Year&quot;)

(p1 + p2) / (p3 + p4) + 
  plot_layout(guides = &quot;collect&quot;)</code></pre>
<p><img src="exercise_final_files/figure-html/unnamed-chunk-6-1.png" width="1248" /></p>
<p><strong>Step Count Distribution:</strong> Daily steps on active days
showed pronounced right-skew with a median of 4,455 steps. The bulk of
observations fell between 2,000-8,000 steps, with a long tail extending
beyond 20,000 steps. The 2024 distribution (orange) shifted notably
rightward compared to 2022 (teal), indicating higher step counts. Five
extreme observations (≥50,000 steps) were excluded from this
visualization only, as they distorted the scale and were obvious data
errors.</p>
<p><strong>Active Minutes Distribution:</strong> Exercise duration
exhibited similar right-skew (52 minutes), with most sessions lasting
20-80 minutes. The 2024 cohort showed longer session durations, with the
distribution peak occurring at higher values than 2022. This pattern
suggests not only more frequent exercise in 2024, but also longer
duration per session.</p>
<p><strong>Calories Burned Distribution:</strong> Energy expenditure
followed the expected pattern given step and duration data (Median = 153
calories). The heavy concentration near zero with gradual right tail
indicates predominantly light-to-moderate intensity exercise, with
occasional high-intensity sessions. The 2024-2022 difference parallels
that observed in steps and active minutes duration.</p>
<p><strong>Exercise Sessions:</strong> Most active days included 1-3
discrete exercise sessions, with a clear mode at 2 sessions. The 2024
cohort showed higher frequencies of 2+ sessions compared to 2022,
suggesting either improved activity tracking or genuinely more
structured exercise routines.</p>
<p>These distributions collectively demonstrate substantial right-skew,
and high variability.</p>
</div>
<div id="activity-type-distribution" class="section level3">
<h3>Activity type distribution</h3>
<pre class="r"><code># Preparing activity types data
activities_long = exercise_analysis |&gt; 
  filter(!is.na(activity_types), activity_types != &quot;&quot;, activity_types != &quot;NA&quot;) |&gt; 
  select(id, study_interval, day_in_study, activity_types) |&gt; 
  mutate(
    # Clean activity types column
    activity_types = str_replace_all(activity_types, &quot;\\n&quot;, &quot;,&quot;),
    activity_types = str_replace_all(activity_types, &quot;\&quot;&quot;, &quot;&quot;)
  ) |&gt; 
  # Split comma-separated activities into rows
  separate_rows(activity_types, sep = &quot;,&quot;) |&gt; 
  mutate(
    activity_types = str_trim(activity_types),
    activity_types = str_to_title(activity_types)
  ) |&gt; 
  filter(activity_types != &quot;&quot;, activity_types != &quot;Na&quot;)

# Counting activities by year
activity_counts = activities_long |&gt; 
  group_by(study_interval, activity_types) |&gt; 
  summarise(n_days = n(), .groups = &quot;drop&quot;) |&gt; 
  group_by(study_interval) |&gt; 
  mutate(pct = n_days / sum(n_days) * 100) |&gt; 
  ungroup()

# Getting top 10 activities
top_activities = activity_counts |&gt; 
  group_by(activity_types) |&gt; 
  summarise(total = sum(n_days)) |&gt; 
  arrange(desc(total)) |&gt; 
  slice(1:10) |&gt; 
  pull(activity_types)

activity_counts_top = activity_counts |&gt; 
  filter(activity_types %in% top_activities)

# Plot: Activity type frequency by year
p1 = ggplot(activity_counts_top, 
             aes(x = reorder(activity_types, pct), y = pct, 
                 fill = factor(study_interval))) +
  geom_col(position = &quot;dodge&quot;, alpha = 0.8) +
  coord_flip() +
  labs(title = &quot;Most Common Activity Types by Study Year&quot;,
       x = &quot;Activity Type&quot;,
       y = &quot;% of Days with Exercise&quot;,
       fill = &quot;Study Year&quot;) +
  theme_minimal() +
  theme(legend.position = &quot;bottom&quot;)

p1</code></pre>
<p><img src="exercise_final_files/figure-html/unnamed-chunk-7-1.png" width="960" />
Walking dominated exercise routines in both study years, accounting for
the vast majority of recorded activity sessions. Beyond walking,
participants engaged in diverse activities including aerobic workouts,
general sport, and strength training (weights). The 2024 cohort showed
greater diversity in activity types, with more structured exercises such
as aerobic workouts and weight training compared to 2022. Activities
like outdoor biking, running, treadmill, and swimming appeared in both
years but at much lower frequencies. Notably, some activities (e.g.,
weights, treadmill, swim, workout, hike) appeared exclusively or
predominantly in 2024.</p>
</div>
<div id="exercise-patterns-across-menstrual-cycle-phases"
class="section level3">
<h3>Exercise patterns across menstrual cycle phases</h3>
<pre class="r"><code>p1 = ggplot(exercise_analysis |&gt; filter(!is.na(phase), total_steps &gt; 0, total_steps &lt; 50000), 
             aes(x = phase, y = total_steps, fill = phase)) +
  geom_boxplot(alpha = 0.7, outlier.alpha = 0.3) +
  geom_jitter(width = 0.2, alpha = 0.1, size = 0.5) +
  stat_summary(fun = mean, geom = &quot;point&quot;, shape = 23, size = 3, fill = &quot;white&quot;) +
  facet_wrap(~study_interval, ncol = 2) +  # Side by side
  labs(title = &quot;Daily Steps by Menstrual Cycle Phase&quot;,
       subtitle = &quot;White diamonds represent mean values | Comparing study years&quot;,
       x = &quot;Cycle Phase&quot;,
       y = &quot;Total Daily Steps&quot;) +
  scale_y_continuous(labels = comma) +
  theme(legend.position = &quot;bottom&quot;,
        axis.text.x = element_text(angle = 45, hjust = 1))

p2 = ggplot(exercise_analysis |&gt; filter(!is.na(phase), total_active_min &gt; 0), 
             aes(x = phase, y = total_active_min, fill = phase)) +
  geom_boxplot(alpha = 0.7, outlier.alpha = 0.3) +
  geom_jitter(width = 0.2, alpha = 0.1, size = 0.5) +
  stat_summary(fun = mean, geom = &quot;point&quot;, shape = 23, size = 3, fill = &quot;white&quot;) +
  facet_wrap(~study_interval, ncol = 2) +
  labs(title = &quot;Active Minutes by Menstrual Cycle Phase&quot;,
       x = &quot;Cycle Phase&quot;,
       y = &quot;Total Active Minutes&quot;) +
  theme(legend.position = &quot;bottom&quot;,
        axis.text.x = element_text(angle = 45, hjust = 1))

p1 / p2 + plot_layout(guides = &quot;collect&quot;)</code></pre>
<p><img src="exercise_final_files/figure-html/unnamed-chunk-8-1.png" width="960" />
Physical activity varied across menstrual cycle phases, with patterns
differing by year. In 2022, activity levels remained relatively stable
across phases, with only slight differences between fertility,
follicular, luteal, and menstrual phases. In contrast, 2024 showed more
pronounced phase-related patterns, with the fertility phase
demonstrating highest activity levels, followed by the follicular phase,
and lower activity during luteal and menstrual phases. Both years
exhibited substantial individual variability, as evident by the wide
spread of data points and multiple outliers, suggesting that not all
participants followed the same phase-related activity patterns. The 2024
cohort showed consistently higher activity across all phases compared to
2022, confirming the year differences observed in overall descriptive
statistics.</p>
</div>
<div id="exercise-vs.-menstrual-symptoms" class="section level3">
<h3>Exercise vs. menstrual symptoms</h3>
<pre class="r"><code>symptoms_long = exercise_analysis |&gt; 
  filter(total_active_min &gt; 0) |&gt; 
  select(id, total_active_min, appetite_score, headaches_score, sorebreasts_score, sleepissue_score, cramps_score, fatigue_score, 
         headaches_score, moodswing_score, foodcravings_score, indigestion_score, bloating_score) |&gt; 
  pivot_longer(cols = ends_with(&quot;_score&quot;), 
               names_to = &quot;symptom&quot;, 
               values_to = &quot;severity&quot;) |&gt; 
  filter(!is.na(severity)) |&gt; 
  mutate(symptom = case_when(
    symptom == &quot;appetite_score&quot; ~ &quot;Appetite&quot;,
    symptom == &quot;headaches_score&quot; ~&quot;Head Aches&quot;,
    symptom == &quot;sorebreasts_score&quot; ~ &quot;Sore Breasts&quot;,
    symptom == &quot;sleepissue_score&quot; ~ &quot;Sleep Issue&quot;,
    symptom == &quot;cramps_score&quot; ~ &quot;Cramps&quot;,
    symptom == &quot;fatigue_score&quot; ~ &quot;Fatigue&quot;,
    symptom == &quot;headaches_score&quot; ~ &quot;Headaches&quot;,
    symptom == &quot;moodswing_score&quot; ~ &quot;Mood Swings&quot;,
    symptom == &quot;foodcravings_score&quot; ~ &quot;Food Cravings&quot;,
    symptom == &quot;indigestion_score&quot; ~ &quot;Indigestion&quot;,
    symptom == &quot;bloating_score&quot; ~ &quot;Bloating&quot;
  ))

p4 = ggplot(symptoms_long, 
             aes(x = total_active_min, y = severity, color = symptom)) +
  geom_jitter(alpha = 0.2, size = 0.5, height = 0.1) +
  geom_smooth(method = &quot;lm&quot;, se = TRUE, linewidth = 1.5, alpha = 0.2) +
  facet_wrap(~symptom, ncol = 2) +
  labs(title = &quot;Daily Activity vs Individual Symptoms&quot;,
       x = &quot;Total Daily Activity (mins)&quot;,
       y = &quot;Symptom Severity (0-5)&quot;) +
  scale_x_continuous(labels = comma) +
  scale_y_continuous(breaks = 0:5) +
  theme(legend.position = &quot;none&quot;)

p4</code></pre>
<p><img src="exercise_final_files/figure-html/unnamed-chunk-9-1.png" width="960" />
The scatterplots examine crude associations between daily activity
(exercise) and each symptom:</p>
<p><strong>Negative slopes (potential benefits):</strong> -
<strong>Bloating</strong>: Modest downward trend suggests higher
activity associates with reduced bloating - <strong>Food
cravings</strong>: Slight negative association, though relationship
appears weak - <strong>Indigestion</strong>: Minimal negative slope with
high variability</p>
<p><strong>Flat relationships (no clear association):</strong> -
<strong>Cramps</strong>: Near-horizontal line despite being primary
outcome - <strong>Appetite, headaches, sleep issues, sore
breasts</strong>: Essentially flat with wide confidence bands -
<strong>Mood swings</strong>: Slight positive but nearly flat, high
uncertainty</p>
<p><strong>Positive slope (likely reverse causation):</strong> -
<strong>Fatigue</strong>: Higher fatigue appears to reduce exercise, not
vice versa</p>
<p><strong>Sleep issues</strong> and <strong>sore breasts</strong>
exhibited insufficient data spread to estimate reliable trends</p>
<p>Across all panels, several key patterns emerge. First, the wide
confidence bands indicate substantial uncertainty in all bivariate
relationships. Second, the considerable scatter reveals that
individual-level associations vary widely, i.e., some participants show
strong exercise-symptom relationships while others show none. Third,
many data points cluster at low activity levels (0-100 minutes), with
sparser observations at higher activity, reflecting the right-skewed
activity distribution. Fourth, symptoms generally concentrate at lower
severity levels (0-2 on 0-5 scale), with relatively few observations at
high severity, consistent with the descriptive statistics.</p>
</div>
<div id="modelling-and-inferential-analysis" class="section level1">
<h1>Modelling and inferential analysis</h1>
<p>We used linear mixed-effects models to test associations between
daily physical activity and menstrual symptom severity. This modeling
approach was necessary because our data violate the independence
assumption of standard linear regression. Mixed-effects models
explicitly account for this hierarchical data structure through random
effects.</p>
<p>For each of 11 symptoms, we fit models with:</p>
<ul>
<li><strong>Outcome</strong>: Symptom severity (0-5 scale)</li>
<li><strong>Predictor</strong>: Total active exercise minutes per
day</li>
<li><strong>Covariate</strong>: Menstrual cycle phase (Menstrual,
Follicular, Fertility, Luteal)</li>
<li><strong>Random effects</strong>: Random intercepts for participants
(1|id)</li>
</ul>
<p>The random intercept structure accounts for repeated measures within
individuals, including the 20 participants (47.6%) who contributed data
in both 2022 and 2024 study intervals. Each participant’s random
intercept captures their baseline symptom tendency, allowing the model
to distinguish between-person effects (do people who exercise more
generally have fewer symptoms?) from within-person effects (on days when
a person exercises more, do they experience fewer symptoms?).</p>
<p>Models were fit using the lme4 package in R with REML = FALSE.
Statistical significance was assessed at α = 0.05.</p>
<pre class="r"><code># Model 1: Exercise → cramps
model_cramps = lmer(cramps_score ~ total_active_min + phase + (1|id), 
                     data = exercise_analysis,
                     REML = FALSE)
summary(model_cramps)</code></pre>
<pre><code>## Linear mixed model fit by maximum likelihood . t-tests use Satterthwaite&#39;s
##   method [lmerModLmerTest]
## Formula: cramps_score ~ total_active_min + phase + (1 | id)
##    Data: exercise_analysis
## 
##       AIC       BIC    logLik -2*log(L)  df.resid 
##    1265.8    1295.1    -625.9    1251.8       480 
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -1.8748 -0.5374 -0.1912  0.2757  4.2158 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev.
##  id       (Intercept) 0.6555   0.8096  
##  Residual             0.6716   0.8195  
## Number of obs: 487, groups:  id, 23
## 
## Fixed effects:
##                    Estimate Std. Error         df t value Pr(&gt;|t|)    
## (Intercept)       6.757e-01  1.947e-01  3.305e+01   3.471  0.00146 ** 
## total_active_min -4.666e-05  1.054e-03  4.686e+02  -0.044  0.96469    
## phasefollicular   7.566e-02  1.106e-01  4.666e+02   0.684  0.49417    
## phaseluteal       5.271e-01  1.059e-01  4.702e+02   4.977 9.08e-07 ***
## phasemenstrual    1.104e+00  1.219e-01  4.712e+02   9.052  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Correlation of Fixed Effects:
##             (Intr) ttl_c_ phsfll phsltl
## totl_ctv_mn -0.220                     
## phasefllclr -0.261 -0.120              
## phaseluteal -0.313  0.010  0.547       
## phasemnstrl -0.282 -0.010  0.464  0.529</code></pre>
<pre class="r"><code># Model 2: Exercise → fatigue
model_fatigue = lmer(fatigue_score ~ total_active_min + phase + (1|id), 
                     data = exercise_analysis,
                     REML = FALSE)
summary(model_fatigue)</code></pre>
<pre><code>## Linear mixed model fit by maximum likelihood . t-tests use Satterthwaite&#39;s
##   method [lmerModLmerTest]
## Formula: fatigue_score ~ total_active_min + phase + (1 | id)
##    Data: exercise_analysis
## 
##       AIC       BIC    logLik -2*log(L)  df.resid 
##    1545.3    1574.7    -765.7    1531.3       483 
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -3.5272 -0.5929 -0.0512  0.6314  3.8870 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev.
##  id       (Intercept) 1.018    1.009   
##  Residual             1.176    1.084   
## Number of obs: 490, groups:  id, 23
## 
## Fixed effects:
##                    Estimate Std. Error         df t value Pr(&gt;|t|)    
## (Intercept)        2.467907   0.246028  34.928340  10.031    8e-12 ***
## total_active_min  -0.002682   0.001361 473.226001  -1.971   0.0493 *  
## phasefollicular    0.260917   0.145952 470.443347   1.788   0.0745 .  
## phaseluteal        0.102270   0.139386 473.823527   0.734   0.4635    
## phasemenstrual     0.293860   0.160674 474.677079   1.829   0.0680 .  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Correlation of Fixed Effects:
##             (Intr) ttl_c_ phsfll phsltl
## totl_ctv_mn -0.234                     
## phasefllclr -0.270 -0.124              
## phaseluteal -0.325  0.014  0.545       
## phasemnstrl -0.295  0.004  0.464  0.527</code></pre>
<pre class="r"><code># Model 3: Exercise → headaches
model_headaches = lmer(headaches_score ~ total_active_min + phase + (1|id), 
                     data = exercise_analysis,
                     REML = FALSE)
summary(model_headaches)</code></pre>
<pre><code>## Linear mixed model fit by maximum likelihood . t-tests use Satterthwaite&#39;s
##   method [lmerModLmerTest]
## Formula: headaches_score ~ total_active_min + phase + (1 | id)
##    Data: exercise_analysis
## 
##       AIC       BIC    logLik -2*log(L)  df.resid 
##    1423.2    1452.5    -704.6    1409.2       478 
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -2.6236 -0.5364 -0.2010  0.4692  4.1854 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev.
##  id       (Intercept) 0.7962   0.8923  
##  Residual             0.9451   0.9721  
## Number of obs: 485, groups:  id, 23
## 
## Fixed effects:
##                    Estimate Std. Error         df t value Pr(&gt;|t|)    
## (Intercept)        1.607615   0.218946  34.723276   7.343 1.46e-08 ***
## total_active_min  -0.002302   0.001252 467.878650  -1.839  0.06648 .  
## phasefollicular    0.138579   0.131170 465.125112   1.056  0.29130    
## phaseluteal        0.190578   0.125562 468.969403   1.518  0.12974    
## phasemenstrual     0.446385   0.144749 469.189552   3.084  0.00216 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Correlation of Fixed Effects:
##             (Intr) ttl_c_ phsfll phsltl
## totl_ctv_mn -0.235                     
## phasefllclr -0.276 -0.119              
## phaseluteal -0.330  0.010  0.547       
## phasemnstrl -0.295 -0.013  0.463  0.528</code></pre>
<pre class="r"><code># Model 4: Exercise → mood swings
model_mood = lmer(moodswing_score ~ total_active_min + phase + (1|id), 
                     data = exercise_analysis,
                     REML = FALSE)
summary(model_mood)</code></pre>
<pre><code>## Linear mixed model fit by maximum likelihood . t-tests use Satterthwaite&#39;s
##   method [lmerModLmerTest]
## Formula: moodswing_score ~ total_active_min + phase + (1 | id)
##    Data: exercise_analysis
## 
##       AIC       BIC    logLik -2*log(L)  df.resid 
##    1404.6    1433.9    -695.3    1390.6       478 
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -3.3104 -0.5034 -0.1327  0.4377  3.8246 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev.
##  id       (Intercept) 1.0026   1.0013  
##  Residual             0.8986   0.9479  
## Number of obs: 485, groups:  id, 23
## 
## Fixed effects:
##                    Estimate Std. Error         df t value Pr(&gt;|t|)    
## (Intercept)        1.836570   0.237305  32.830978   7.739 6.71e-09 ***
## total_active_min  -0.001123   0.001221 467.100818  -0.919   0.3585    
## phasefollicular    0.031829   0.127959 465.057240   0.249   0.8037    
## phaseluteal        0.187347   0.122554 468.127353   1.529   0.1270    
## phasemenstrual     0.334806   0.141285 468.285367   2.370   0.0182 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Correlation of Fixed Effects:
##             (Intr) ttl_c_ phsfll phsltl
## totl_ctv_mn -0.211                     
## phasefllclr -0.248 -0.119              
## phaseluteal -0.297  0.010  0.547       
## phasemnstrl -0.265 -0.013  0.463  0.528</code></pre>
<pre class="r"><code># Model 5: Exercise → sleep issues
model_sleep = lmer(sleepissue_score ~ total_active_min + phase + (1|id), 
                     data = exercise_analysis,
                     REML = FALSE)
summary(model_sleep)</code></pre>
<pre><code>## Linear mixed model fit by maximum likelihood . t-tests use Satterthwaite&#39;s
##   method [lmerModLmerTest]
## Formula: sleepissue_score ~ total_active_min + phase + (1 | id)
##    Data: exercise_analysis
## 
##       AIC       BIC    logLik -2*log(L)  df.resid 
##    1468.4    1497.8    -727.2    1454.4       481 
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -3.0889 -0.4629 -0.2024  0.5656  3.2474 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev.
##  id       (Intercept) 0.9732   0.9865  
##  Residual             1.0127   1.0063  
## Number of obs: 488, groups:  id, 23
## 
## Fixed effects:
##                    Estimate Std. Error         df t value Pr(&gt;|t|)    
## (Intercept)       2.124e+00  2.376e-01  3.279e+01   8.941 2.61e-10 ***
## total_active_min -3.841e-04  1.266e-03  4.705e+02  -0.303    0.762    
## phasefollicular  -1.654e-01  1.358e-01  4.674e+02  -1.219    0.224    
## phaseluteal      -8.634e-02  1.300e-01  4.711e+02  -0.664    0.507    
## phasemenstrual    1.314e-01  1.495e-01  4.716e+02   0.879    0.380    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Correlation of Fixed Effects:
##             (Intr) ttl_c_ phsfll phsltl
## totl_ctv_mn -0.222                     
## phasefllclr -0.262 -0.127              
## phaseluteal -0.315  0.010  0.547       
## phasemnstrl -0.286  0.001  0.466  0.529</code></pre>
<pre class="r"><code># Model 6: Exercise → bloating
model_bloating = lmer(bloating_score ~ total_active_min + phase + (1|id), 
                     data = exercise_analysis,
                     REML = FALSE)
summary(model_bloating)</code></pre>
<pre><code>## Linear mixed model fit by maximum likelihood . t-tests use Satterthwaite&#39;s
##   method [lmerModLmerTest]
## Formula: bloating_score ~ total_active_min + phase + (1 | id)
##    Data: exercise_analysis
## 
##       AIC       BIC    logLik -2*log(L)  df.resid 
##    1352.9    1382.3    -669.5    1338.9       481 
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -3.2181 -0.4062 -0.1555  0.2982  3.2756 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev.
##  id       (Intercept) 1.1441   1.0696  
##  Residual             0.7848   0.8859  
## Number of obs: 488, groups:  id, 23
## 
## Fixed effects:
##                    Estimate Std. Error         df t value Pr(&gt;|t|)    
## (Intercept)       1.612e+00  2.465e-01  3.043e+01   6.542  2.9e-07 ***
## total_active_min -2.529e-04  1.116e-03  4.693e+02  -0.227 0.820856    
## phasefollicular  -3.568e-03  1.196e-01  4.673e+02  -0.030 0.976212    
## phaseluteal       3.841e-01  1.146e-01  4.699e+02   3.351 0.000871 ***
## phasemenstrual    4.009e-01  1.318e-01  4.702e+02   3.042 0.002480 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Correlation of Fixed Effects:
##             (Intr) ttl_c_ phsfll phsltl
## totl_ctv_mn -0.188                     
## phasefllclr -0.222 -0.126              
## phaseluteal -0.267  0.011  0.547       
## phasemnstrl -0.243  0.001  0.466  0.529</code></pre>
<pre class="r"><code># Model 7: Exercise → appetite
model_appetite = lmer(appetite_score ~ total_active_min + phase + (1|id), 
                     data = exercise_analysis,
                     REML = FALSE)
summary(model_appetite)</code></pre>
<pre><code>## Linear mixed model fit by maximum likelihood . t-tests use Satterthwaite&#39;s
##   method [lmerModLmerTest]
## Formula: appetite_score ~ total_active_min + phase + (1 | id)
##    Data: exercise_analysis
## 
##       AIC       BIC    logLik -2*log(L)  df.resid 
##    1112.0    1141.4    -549.0    1098.0       483 
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -3.5900 -0.7095 -0.0207  0.5041  2.7077 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev.
##  id       (Intercept) 0.2401   0.4900  
##  Residual             0.4974   0.7053  
## Number of obs: 490, groups:  id, 23
## 
## Fixed effects:
##                    Estimate Std. Error         df t value Pr(&gt;|t|)    
## (Intercept)       2.875e+00  1.313e-01  4.300e+01  21.895   &lt;2e-16 ***
## total_active_min  3.267e-04  8.830e-04  4.767e+02   0.370   0.7116    
## phasefollicular  -1.619e-01  9.482e-02  4.720e+02  -1.707   0.0885 .  
## phaseluteal      -9.643e-03  9.044e-02  4.768e+02  -0.107   0.9151    
## phasemenstrual   -5.397e-02  1.042e-01  4.782e+02  -0.518   0.6048    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Correlation of Fixed Effects:
##             (Intr) ttl_c_ phsfll phsltl
## totl_ctv_mn -0.286                     
## phasefllclr -0.330 -0.125              
## phaseluteal -0.397  0.013  0.546       
## phasemnstrl -0.358  0.003  0.465  0.527</code></pre>
<pre class="r"><code># Model 8: Exercise → sore breasts
model_sorebreasts = lmer(sorebreasts_score ~ total_active_min + phase + (1|id), 
                     data = exercise_analysis,
                     REML = FALSE)
summary(model_sorebreasts)</code></pre>
<pre><code>## Linear mixed model fit by maximum likelihood . t-tests use Satterthwaite&#39;s
##   method [lmerModLmerTest]
## Formula: sorebreasts_score ~ total_active_min + phase + (1 | id)
##    Data: exercise_analysis
## 
##       AIC       BIC    logLik -2*log(L)  df.resid 
##    1095.2    1124.5    -540.6    1081.2       480 
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -2.5866 -0.4788 -0.0787  0.1664  4.8257 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev.
##  id       (Intercept) 0.5941   0.7708  
##  Residual             0.4677   0.6839  
## Number of obs: 487, groups:  id, 23
## 
## Fixed effects:
##                    Estimate Std. Error         df t value Pr(&gt;|t|)    
## (Intercept)       6.654e-01  1.800e-01  3.165e+01   3.697 0.000823 ***
## total_active_min  4.040e-04  8.798e-04  4.682e+02   0.459 0.646285    
## phasefollicular  -2.127e-02  9.232e-02  4.666e+02  -0.230 0.817881    
## phaseluteal       2.371e-01  8.845e-02  4.696e+02   2.681 0.007601 ** 
## phasemenstrual    4.254e-01  1.018e-01  4.703e+02   4.177 3.52e-05 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Correlation of Fixed Effects:
##             (Intr) ttl_c_ phsfll phsltl
## totl_ctv_mn -0.198                     
## phasefllclr -0.235 -0.120              
## phaseluteal -0.282  0.010  0.547       
## phasemnstrl -0.255 -0.010  0.464  0.529</code></pre>
<pre class="r"><code># Model 9: Exercise → food cravings
model_foodcravings = lmer(foodcravings_score ~ total_active_min + phase + (1|id), 
                     data = exercise_analysis,
                     REML = FALSE)
summary(model_foodcravings)</code></pre>
<pre><code>## Linear mixed model fit by maximum likelihood . t-tests use Satterthwaite&#39;s
##   method [lmerModLmerTest]
## Formula: foodcravings_score ~ total_active_min + phase + (1 | id)
##    Data: exercise_analysis
## 
##       AIC       BIC    logLik -2*log(L)  df.resid 
##    1532.1    1561.5    -759.1    1518.1       480 
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -2.8215 -0.4849 -0.0844  0.4775  2.9251 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev.
##  id       (Intercept) 1.149    1.072   
##  Residual             1.160    1.077   
## Number of obs: 487, groups:  id, 23
## 
## Fixed effects:
##                    Estimate Std. Error         df t value Pr(&gt;|t|)    
## (Intercept)        2.025357   0.257233  33.122162   7.874 4.34e-09 ***
## total_active_min  -0.001306   0.001385 468.676043  -0.943   0.3462    
## phasefollicular   -0.152891   0.145321 466.671362  -1.052   0.2933    
## phaseluteal        0.278339   0.139177 470.236078   2.000   0.0461 *  
## phasemenstrual     0.071820   0.160225 471.231603   0.448   0.6542    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Correlation of Fixed Effects:
##             (Intr) ttl_c_ phsfll phsltl
## totl_ctv_mn -0.219                     
## phasefllclr -0.259 -0.120              
## phaseluteal -0.311  0.010  0.547       
## phasemnstrl -0.281 -0.010  0.464  0.529</code></pre>
<pre class="r"><code># Model 10: Exercise → indigestion
model_indigestion = lmer(indigestion_score ~ total_active_min + phase + (1|id), 
                     data = exercise_analysis,
                     REML = FALSE)
summary(model_indigestion)</code></pre>
<pre><code>## Linear mixed model fit by maximum likelihood . t-tests use Satterthwaite&#39;s
##   method [lmerModLmerTest]
## Formula: indigestion_score ~ total_active_min + phase + (1 | id)
##    Data: exercise_analysis
## 
##       AIC       BIC    logLik -2*log(L)  df.resid 
##    1382.3    1411.7    -684.2    1368.3       480 
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -2.4525 -0.3690 -0.1614  0.1884  3.5885 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev.
##  id       (Intercept) 1.0583   1.0288  
##  Residual             0.8439   0.9187  
## Number of obs: 487, groups:  id, 23
## 
## Fixed effects:
##                    Estimate Std. Error         df t value Pr(&gt;|t|)    
## (Intercept)        1.457001   0.240530  30.800642   6.057 1.07e-06 ***
## total_active_min  -0.001599   0.001182 467.608774  -1.353  0.17663    
## phasefollicular    0.126242   0.124003 466.027077   1.018  0.30918    
## phaseluteal        0.355403   0.118810 469.054074   2.991  0.00292 ** 
## phasemenstrual     0.312394   0.136794 469.868346   2.284  0.02284 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Correlation of Fixed Effects:
##             (Intr) ttl_c_ phsfll phsltl
## totl_ctv_mn -0.199                     
## phasefllclr -0.236 -0.120              
## phaseluteal -0.284  0.010  0.547       
## phasemnstrl -0.257 -0.010  0.464  0.529</code></pre>
<pre class="r"><code># Cleaning results:
# Extracting coefficients for exercise effect
results_summary = bind_rows(
  tidy(model_cramps, effects = &quot;fixed&quot;) %&gt;% mutate(outcome = &quot;Cramps&quot;),
  tidy(model_fatigue, effects = &quot;fixed&quot;) %&gt;% mutate(outcome = &quot;Fatigue&quot;),
  tidy(model_headaches, effects = &quot;fixed&quot;) %&gt;% mutate(outcome = &quot;Head Aches&quot;),
  tidy(model_mood, effects = &quot;fixed&quot;) %&gt;% mutate(outcome = &quot;Mood Swings&quot;),
  tidy(model_sleep, effects = &quot;fixed&quot;) %&gt;% mutate(outcome = &quot;Sleep Issues&quot;),
  tidy(model_bloating, effects = &quot;fixed&quot;) %&gt;% mutate(outcome = &quot;Bloating&quot;),
  tidy(model_appetite, effects = &quot;fixed&quot;) %&gt;% mutate(outcome = &quot;Appetite&quot;),
  tidy(model_indigestion, effects = &quot;fixed&quot;) %&gt;% mutate(outcome = &quot;Indigestion&quot;),
  tidy(model_sorebreasts, effects = &quot;fixed&quot;) %&gt;% mutate(outcome = &quot;Sore breasts&quot;),
  tidy(model_foodcravings, effects = &quot;fixed&quot;) %&gt;% mutate(outcome = &quot;Food cravings&quot;)
) %&gt;%
  filter(term == &quot;total_active_min&quot;) %&gt;%
  select(outcome, estimate, std.error, statistic, p.value) %&gt;%
  mutate(
    significant = ifelse(p.value &lt; 0.05, &quot;Yes&quot;, &quot;No&quot;),
    p.value = format.pval(p.value, digits = 3, eps = 0.001)
  )

knitr::kable(results_summary)</code></pre>
<table>
<colgroup>
<col width="21%" />
<col width="16%" />
<col width="15%" />
<col width="16%" />
<col width="12%" />
<col width="18%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">outcome</th>
<th align="right">estimate</th>
<th align="right">std.error</th>
<th align="right">statistic</th>
<th align="left">p.value</th>
<th align="left">significant</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Cramps</td>
<td align="right">-0.0000467</td>
<td align="right">0.0010536</td>
<td align="right">-0.0442889</td>
<td align="left">0.9647</td>
<td align="left">No</td>
</tr>
<tr class="even">
<td align="left">Fatigue</td>
<td align="right">-0.0026819</td>
<td align="right">0.0013608</td>
<td align="right">-1.9708807</td>
<td align="left">0.0493</td>
<td align="left">Yes</td>
</tr>
<tr class="odd">
<td align="left">Head Aches</td>
<td align="right">-0.0023021</td>
<td align="right">0.0012515</td>
<td align="right">-1.8394980</td>
<td align="left">0.0665</td>
<td align="left">No</td>
</tr>
<tr class="even">
<td align="left">Mood Swings</td>
<td align="right">-0.0011226</td>
<td align="right">0.0012213</td>
<td align="right">-0.9191398</td>
<td align="left">0.3585</td>
<td align="left">No</td>
</tr>
<tr class="odd">
<td align="left">Sleep Issues</td>
<td align="right">-0.0003841</td>
<td align="right">0.0012664</td>
<td align="right">-0.3033156</td>
<td align="left">0.7618</td>
<td align="left">No</td>
</tr>
<tr class="even">
<td align="left">Bloating</td>
<td align="right">-0.0002529</td>
<td align="right">0.0011161</td>
<td align="right">-0.2265707</td>
<td align="left">0.8209</td>
<td align="left">No</td>
</tr>
<tr class="odd">
<td align="left">Appetite</td>
<td align="right">0.0003267</td>
<td align="right">0.0008830</td>
<td align="right">0.3699452</td>
<td align="left">0.7116</td>
<td align="left">No</td>
</tr>
<tr class="even">
<td align="left">Indigestion</td>
<td align="right">-0.0015992</td>
<td align="right">0.0011818</td>
<td align="right">-1.3532633</td>
<td align="left">0.1766</td>
<td align="left">No</td>
</tr>
<tr class="odd">
<td align="left">Sore breasts</td>
<td align="right">0.0004040</td>
<td align="right">0.0008798</td>
<td align="right">0.4592262</td>
<td align="left">0.6463</td>
<td align="left">No</td>
</tr>
<tr class="even">
<td align="left">Food cravings</td>
<td align="right">-0.0013056</td>
<td align="right">0.0013846</td>
<td align="right">-0.9429113</td>
<td align="left">0.3462</td>
<td align="left">No</td>
</tr>
</tbody>
</table>
<p>Linear mixed-effects models showed limited evidence for associations
between daily physical activity and menstrual symptom severity after
controlling for cycle phase and individual differences. Of the 11
symptoms examined, only fatigue showed statistically significant
relationships with exercise at α = 0.05: fatigue (β = -0.0026819 , SE =
0.0013608, p = 0.0493).</p>
<p>For fatigue, the negative coefficient indicates that each additional
minute of daily active exercise was associated with a 0.0027 point
decrease in fatigue severity on the 0-5 scale.</p>
<p>The remaining 9 symptoms showed no significant associations with
exercise. Effect estimates for these symptoms were near-zero with
confidence intervals spanning positive and negative values, indicating
no detectable relationship between daily exercise and symptom severity
after controlling for menstrual cycle phase.</p>
<p>Interestingly, cramps, the primary outcome of interest given its
prominence in menstrual symptom research, showed essentially no
association with exercise (β = -0.00005, p = 0.9647). The point estimate
had wide confidence intervals indicating no evidence of either
beneficial or harmful effects.</p>
<div id="model-diagnostics" class="section level3">
<h3>Model Diagnostics</h3>
<pre class="r"><code># Three essential plots
par(mfrow = c(1, 3))

# 1. Residuals vs Fitted (linearity + homoscedasticity)
plot(fitted(model_fatigue), resid(model_fatigue),
     xlab = &quot;Fitted Values&quot;, ylab = &quot;Residuals&quot;,
     main = &quot;Residuals vs Fitted&quot;,
     pch = 16, col = rgb(0, 0, 0, 0.3))
abline(h = 0, col = &quot;red&quot;, lty = 2, lwd = 2)

# 2. Q-Q Plot (normality of residuals)
qqnorm(resid(model_cramps), main = &quot;Q-Q Plot: Residuals&quot;,
       pch = 16, col = rgb(0, 0, 0, 0.3))
qqline(resid(model_cramps), col = &quot;red&quot;, lwd = 2)

# 3. Q-Q Plot (normality of random effects)
qqnorm(ranef(model_cramps)$id[,1], main = &quot;Q-Q Plot: Random Effects&quot;,
       pch = 16, col = rgb(0, 0, 0, 0.5))
qqline(ranef(model_cramps)$id[,1], col = &quot;red&quot;, lwd = 2)</code></pre>
<p><img src="exercise_final_files/figure-html/model-diagnostics-1.png" width="960" /></p>
<pre class="r"><code>par(mfrow = c(1, 1))</code></pre>
<p>The residual vs fitted plot shows diagonal banding typical of ordinal
outcome data (symptom scores are discrete: 0, 1, 2, 3, 4, 5). This is
expected when applying linear models to Likert-scale data. The Q-Q plots
indicate that residuals and random effects are approximately normally
distributed, supporting the use of mixed-effects models.</p>
</div>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->
<script>
$(document).ready(function () {
  window.initializeCodeFolding("show" === "show");
});
</script>


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
