<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>hormone</title>

<script src="site_libs/header-attrs-2.29/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/readable.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.13.2/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/navigation-1.1/codefolding.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/font-awesome-6.5.2/css/all.min.css" rel="stylesheet" />
<link href="site_libs/font-awesome-6.5.2/css/v4-shims.min.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->
<style type="text/css">
.code-folding-btn { margin-bottom: 4px; }
</style>



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html"></a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">
    <span class="fa fa-solid fa-spa"></span>
     
  </a>
</li>
<li>
  <a href="report.html">Report</a>
</li>
<li>
  <a href="data.html">Data</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Lifestyle Factors Analyses
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="hormone_final.html">Hormone &amp; Symptoms</a>
    </li>
    <li>
      <a href="sleep_stress_khue.html">Sleep &amp; Stress</a>
    </li>
    <li>
      <a href="exercise_hormone.html">Exercise</a>
    </li>
  </ul>
</li>
<li>
  <a href="p8105_final_project_proposal.html">Proposal</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="about.html">Meet the Team</a>
</li>
<li>
  <a>
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">

<div class="btn-group pull-right float-right">
<button type="button" class="btn btn-default btn-xs btn-secondary btn-sm dropdown-toggle" data-toggle="dropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
<ul class="dropdown-menu dropdown-menu-right" style="min-width: 50px;">
<li><a id="rmd-show-all-code" href="#">Show All Code</a></li>
<li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li>
</ul>
</div>



<h1 class="title toc-ignore">hormone</h1>

</div>


<p>##yue’s interest: phase, lh, estrogen, moodswing, fatigue</p>
<p>first, explore relationship between LH and estrogen
<img src="hormone_files/figure-html/unnamed-chunk-4-1.png" width="672" />
EDA Average hormone profiles varied systematically across menstrual
cycle phases. Estrogen exhibited a clear surge during the Fertility
(ovulatory) phase, while LH showed a small peak at the same phase,
consistent with the known physiological LH surge that triggers
ovulation. Both hormones were relatively low during the Menstrual phase
and increased through the Follicular phase before peaking in Fertility,
then declining during the Luteal phase. These patterns confirm that the
hormonal data capture biologically meaningful endocrine rhythms across
the cycle.</p>
<p>fatigue and moodswing</p>
<p>##this two bar graph show the proportion of fatigue and moodswing
among four phases, but they are hard to read.</p>
<p>#so i aim to change the catogorical value (low, moderate, high) to
1,2,3, and so on. i want to sum and avrage. to show a typical cahnge of
fatigue and mood in four phases.</p>
<p><img src="hormone_files/figure-html/unnamed-chunk-7-1.png" width="672" />
<img src="hormone_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<p>violin graphs for moodswing</p>
<pre><code>## Warning: Removed 544 rows containing missing values or values
## outside the scale range (`geom_point()`).</code></pre>
<p><img src="hormone_files/figure-html/unnamed-chunk-9-1.png" width="672" />
violin for fatigue</p>
<pre><code>## Warning: Removed 331 rows containing missing values or values
## outside the scale range (`geom_point()`).</code></pre>
<p><img src="hormone_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<p>Both mood swing and fatigue showed clear phase-dependent variation.
After converting ordinal symptom ratings into numeric intensity scores,
average mood swing and fatigue levels were highest during the Menstrual
phase and lowest during the Follicular phase. Violin plots revealed
substantial inter-individual variability but consistent right-skewed
distributions during Menstrual and Luteal phases, indicating higher
symptom burden during these periods.</p>
<div id="approach-longtidual-changes" class="section level1">
<h1>approach: longtidual changes</h1>
<pre><code>## Linear mixed model fit by REML. t-tests use Satterthwaite&#39;s method [
## lmerModLmerTest]
## Formula: moodswing_num ~ phase + (1 | id)
##    Data: my_int_numeric
## 
## REML criterion at convergence: 8506.2
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -3.0689 -0.5616 -0.1457  0.4561  4.1382 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev.
##  id       (Intercept) 1.051    1.025   
##  Residual             1.091    1.044   
## Number of obs: 2846, groups:  id, 42
## 
## Fixed effects:
##                  Estimate Std. Error         df t value Pr(&gt;|t|)    
## (Intercept)     1.464e+00  1.633e-01  4.512e+01   8.967 1.38e-11 ***
## phaseFertility -2.881e-03  5.783e-02  2.805e+03  -0.050   0.9603    
## phaseLuteal     1.319e-01  5.299e-02  2.807e+03   2.489   0.0129 *  
## phaseMenstrual  3.584e-01  6.118e-02  2.806e+03   5.858 5.24e-09 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Correlation of Fixed Effects:
##             (Intr) phsFrt phsLtl
## phaseFrtlty -0.166              
## phaseLuteal -0.184  0.525       
## phaseMnstrl -0.159  0.457  0.506</code></pre>
<pre><code>## Linear mixed model fit by REML. t-tests use Satterthwaite&#39;s method [
## lmerModLmerTest]
## Formula: fatigue_num ~ phase + (1 | id)
##    Data: my_int_numeric
## 
## REML criterion at convergence: 7930.3
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -3.1591 -0.6811 -0.0214  0.5734  3.6953 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev.
##  id       (Intercept) 0.4885   0.6989  
##  Residual             0.8978   0.9475  
## Number of obs: 2846, groups:  id, 42
## 
## Fixed effects:
##                  Estimate Std. Error         df t value Pr(&gt;|t|)    
## (Intercept)     1.803e+00  1.140e-01  4.746e+01  15.817  &lt; 2e-16 ***
## phaseFertility -3.221e-03  5.246e-02  2.806e+03  -0.061    0.951    
## phaseLuteal     6.817e-02  4.806e-02  2.811e+03   1.418    0.156    
## phaseMenstrual  2.740e-01  5.549e-02  2.809e+03   4.937 8.39e-07 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Correlation of Fixed Effects:
##             (Intr) phsFrt phsLtl
## phaseFrtlty -0.216              
## phaseLuteal -0.239  0.525       
## phaseMnstrl -0.206  0.457  0.506</code></pre>
<p>Longitudinal Mixed-Effects Modeling of Symptoms</p>
<p>To account for repeated measurements within individuals, linear
mixed-effects models with random intercepts for participant ID were
fitted. For mood swings, relative to the Follicular phase, the Luteal
phase showed a significant increase of approximately +0.13 units (t =
2.49), while the Menstrual phase showed a much larger increase of
approximately +0.36 units (t = 5.86). For fatigue, only the Menstrual
phase differed significantly from the Follicular phase, with an increase
of approximately +0.27 units (t = 4.94); Fertility and Luteal phases
showed negligible and non-significant differences. These results
demonstrate that within individuals, mood disturbances and fatigue are
most strongly elevated during the Menstrual phase.</p>
<p>reletionship between hormone and flow color, flow volume, and
appetite</p>
<p>Overall scatter plot for three variables:</p>
<pre><code>## Warning: Removed 460 rows containing non-finite outside the scale
## range (`stat_summary()`).
## Removed 460 rows containing non-finite outside the scale
## range (`stat_summary()`).</code></pre>
<pre><code>## Warning: Removed 460 rows containing missing values or values
## outside the scale range (`geom_point()`).</code></pre>
<p><img src="hormone_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
<pre><code>## Warning: Removed 510 rows containing non-finite outside the scale
## range (`stat_summary()`).</code></pre>
<pre><code>## Warning: Removed 510 rows containing non-finite outside the scale
## range (`stat_summary()`).</code></pre>
<pre><code>## Warning: Removed 510 rows containing missing values or values
## outside the scale range (`geom_point()`).</code></pre>
<p><img src="hormone_files/figure-html/unnamed-chunk-14-2.png" width="672" /></p>
<pre><code>## Warning: Removed 226 rows containing non-finite outside the scale
## range (`stat_summary()`).</code></pre>
<pre><code>## Warning: Removed 226 rows containing non-finite outside the scale
## range (`stat_summary()`).</code></pre>
<pre><code>## Warning: Removed 226 rows containing missing values or values
## outside the scale range (`geom_point()`).</code></pre>
<p><img src="hormone_files/figure-html/unnamed-chunk-14-3.png" width="672" /></p>
<p><img src="hormone_files/figure-html/unnamed-chunk-16-1.png" width="672" /><img src="hormone_files/figure-html/unnamed-chunk-16-2.png" width="672" /><img src="hormone_files/figure-html/unnamed-chunk-16-3.png" width="672" />
add violin data:</p>
<pre><code>## Warning: Removed 2567 rows containing non-finite outside the scale
## range (`stat_ydensity()`).</code></pre>
<p><img src="hormone_files/figure-html/unnamed-chunk-17-1.png" width="672" /></p>
<pre><code>## NULL</code></pre>
<pre><code>## Warning: Removed 2617 rows containing non-finite outside the scale
## range (`stat_ydensity()`).</code></pre>
<p><img src="hormone_files/figure-html/unnamed-chunk-18-1.png" width="672" /></p>
<pre><code>## Warning: Removed 2333 rows containing non-finite outside the scale
## range (`stat_ydensity()`).</code></pre>
<p><img src="hormone_files/figure-html/unnamed-chunk-19-1.png" width="672" /></p>
<p>#Flow volume &amp; flow color: There are clear differences across
menstrual cycle phases. Likely patterns: heavier flow and darker color
in the Menstrual phase, lighter/spotting in Follicular/Luteal.</p>
<p>#Appetite:Overall differences across phases are not statistically
significant at α = 0.05. There may be a trend, but the variation is
smaller or more individual-specific.</p>
<p>To account for within-subject repeated measures and get
phase-specific effects, we can fit CLMM models:</p>
<pre><code>## Cumulative Link Mixed Model fitted with the Laplace approximation
## 
## formula: flow_volume ~ phase + (1 | id)
## data:    other_interest
## 
##  link  threshold nobs logLik   AIC     niter     max.grad cond.H 
##  logit flexible  3091 -1801.42 3622.83 824(3300) 2.08e-03 1.6e+02
## 
## Random effects:
##  Groups Name        Variance Std.Dev.
##  id     (Intercept) 0.8281   0.91    
## Number of groups:  id 42 
## 
## Coefficients:
##                Estimate Std. Error z value Pr(&gt;|z|)    
## phaseFertility  -1.5928     0.2016   -7.90 2.79e-15 ***
## phaseLuteal     -2.1400     0.2072  -10.33  &lt; 2e-16 ***
## phaseMenstrual   3.1333     0.1423   22.02  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Threshold coefficients:
##                                  Estimate Std. Error z value
## Not at all|Spotting / Very Light   1.5725     0.1712   9.183
## Spotting / Very Light|Light        2.5094     0.1802  13.926
## Light|Moderate                     3.3266     0.1904  17.475
## Moderate|Somewhat Heavy            4.4350     0.2065  21.475
## Somewhat Heavy|Heavy               5.2151     0.2229  23.396
## Heavy|Very Heavy                   6.5315     0.2810  23.241
## (2568 observations deleted due to missingness)</code></pre>
<pre><code>## Warning in update.uC(rho): Non finite negative log-likelihood
##   at iteration 48</code></pre>
<pre><code>## Cumulative Link Mixed Model fitted with the Laplace approximation
## 
## formula: flow_color ~ phase + (1 | id)
## data:    other_interest
## 
##  link  threshold nobs logLik   AIC     niter     max.grad cond.H 
##  logit flexible  3041 -1733.01 3486.03 891(3564) 2.66e-03 7.1e+02
## 
## Random effects:
##  Groups Name        Variance Std.Dev.
##  id     (Intercept) 0.5171   0.7191  
## Number of groups:  id 42 
## 
## Coefficients:
##                Estimate Std. Error z value Pr(&gt;|z|)    
## phaseFertility  -1.5180     0.2029  -7.481 7.39e-14 ***
## phaseLuteal     -2.8931     0.2764 -10.467  &lt; 2e-16 ***
## phaseMenstrual   2.1435     0.1280  16.751  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Threshold coefficients:
##                                  Estimate Std. Error z value
## Not at all|Pink                    1.3511     0.1493   9.048
## Pink|Bright Red                    1.4809     0.1506   9.835
## Bright Red|Dark Brown / Dark Red   2.3963     0.1586  15.105
## Dark Brown / Dark Red|Grey         4.3868     0.1903  23.053
## Grey|Black                         4.4633     0.1926  23.178
## Black|Other                        4.5598     0.1957  23.306
## (2618 observations deleted due to missingness)</code></pre>
<pre><code>## Cumulative Link Mixed Model fitted with the Laplace approximation
## 
## formula: appetite ~ phase + (1 | id)
## data:    other_interest
## 
##  link  threshold nobs logLik   AIC     niter     max.grad cond.H 
##  logit flexible  3325 -3615.00 7246.01 603(2993) 1.73e-03 9.3e+01
## 
## Random effects:
##  Groups Name        Variance Std.Dev.
##  id     (Intercept) 1.398    1.183   
## Number of groups:  id 42 
## 
## Coefficients:
##                Estimate Std. Error z value Pr(&gt;|z|)    
## phaseFertility  0.15449    0.09975   1.549    0.121    
## phaseLuteal     0.36579    0.09154   3.996 6.44e-05 ***
## phaseMenstrual  0.11871    0.10475   1.133    0.257    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Threshold coefficients:
##                Estimate Std. Error z value
## Very Low|Low    -3.5037     0.2132 -16.431
## Low|Moderate    -1.0604     0.1971  -5.381
## Moderate|High    1.8759     0.1989   9.430
## High|Very High   4.3591     0.2249  19.384
## (2334 observations deleted due to missingness)</code></pre>
<p>#interpretation: Flow volume: The relatively low AIC (3622.83)
compared with the other models indicates a strong phase-dependent
structure in flow volume.Because flow volume is directly driven by
bleeding physiology, the good model fit supports that menstrual phase is
the dominant determinant of bleeding intensity.</p>
<p>Flow color: The lowest AIC across all three models (3486.03)
indicates that flow color is even more strongly phase-locked than flow
volume.</p>
<p>Appetite: Model converged very well (low gradient, strong Hessian
stability). The random intercept variance for individual appetite
baseline was: Variance = 1.398, SD = 1.183, 42 individuals. This
indicates large between-person differences in baseline appetite,
confirming the necessity of mixed-effects modeling instead of
independent-sample methods.</p>
<p>Conclusion: Flow volume is strongly structured by menstrual phase,
with the cleanest signal among all three outcomes.</p>
<p>Flow color is the most phase-sensitive outcome in your entire
dataset, tightly anchored to menstrual cycle transitions.</p>
<p>Only the Luteal phase showed a statistically significant increase in
appetite relative to the Follicular phase, This estimate is on the
log-odds scale, meaning that the odds of reporting higher appetite
categories increase substantially in the Luteal phase within the same
individuals. Appetite did not differ significantly in the fertility and
menstrual phase. This confirms that appetite elevation is a
Luteal-specific physiological effect, not a general cycle-wide
fluctuation.</p>
<p>Clustering:
<img src="hormone_files/figure-html/unnamed-chunk-21-1.png" width="672" /></p>
<pre><code>## # A tibble: 3 × 7
##   cluster    lh estrogen moodswing_num fatigue_num appetite_num flow_volume_num
##   &lt;fct&gt;   &lt;dbl&gt;    &lt;dbl&gt;         &lt;dbl&gt;       &lt;dbl&gt;        &lt;dbl&gt;           &lt;dbl&gt;
## 1 1        3.82     101.          1.85        2.08         1.92           2.45 
## 2 2       11.5      256.          1.45        1.93         2.14           0.212
## 3 3        4.58     119.          1.47        1.82         1.83           0.146</code></pre>
<p>Unsupervised k-means clustering applied to six standardized features
(LH, estrogen, mood swing, fatigue, appetite, and flow volume)
identified three distinct physiological–symptom phenotypes:</p>
<p>Cluster 1 (Menstrual–High Symptom–High Flow Group) was characterized
by low hormones (LH = 3.82, estrogen = 101.00), the highest mood swing
(1.85) and fatigue (2.08), and markedly elevated flow volume (2.45).</p>
<p>Cluster 2 (Ovulatory–High Hormone–High Appetite Group) showed
extremely high hormones (LH = 11.47, estrogen = 256.48), the highest
appetite (2.14), low mood swing (1.45) and fatigue (1.93), and minimal
flow (0.21).</p>
<p>Cluster 3 (Baseline–Low Symptom Group) exhibited moderate hormone
levels (LH = 4.58, estrogen = 119.21), the lowest mood swing (1.47) and
fatigue (1.82), stable appetite (1.83), and minimal flow (0.15).</p>
<p>These clusters closely align with known biological states of the
menstrual cycle, corresponding to menstrual symptomatic states,
ovulatory high-hormone states, and baseline low-symptom states.</p>
<p>Overall final results: Flow volume and flow color exhibited the
strongest phase-locking across the menstrual cycle, while appetite
showed a robust, individual-specific increase restricted to the Luteal
phase, with substantial between-person variability dominating overall
appetite levels.</p>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->
<script>
$(document).ready(function () {
  window.initializeCodeFolding("show" === "show");
});
</script>

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
