<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />



<meta name="date" content="2025-12-03" />

<title>hormone_final</title>

<script src="site_libs/header-attrs-2.29/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/readable.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.13.2/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/navigation-1.1/codefolding.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/font-awesome-6.5.2/css/all.min.css" rel="stylesheet" />
<link href="site_libs/font-awesome-6.5.2/css/v4-shims.min.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->
<style type="text/css">
.code-folding-btn { margin-bottom: 4px; }
</style>



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html"></a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">
    <span class="fa fa-solid fa-spa"></span>
     
  </a>
</li>
<li>
  <a href="report.html">Report</a>
</li>
<li>
  <a href="data.html">Data</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Lifestyle Factors Analyses
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="hormone.html">Hormone &amp; Symptoms</a>
    </li>
    <li>
      <a href="sleep_stress_khue.html">Sleep &amp; Stress</a>
    </li>
    <li>
      <a href="exercise_hormone.html">Exercise</a>
    </li>
  </ul>
</li>
<li>
  <a href="p8105_final_project_proposal.html">Proposal</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="about.html">Meet the Team</a>
</li>
<li>
  <a>
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">

<div class="btn-group pull-right float-right">
<button type="button" class="btn btn-default btn-xs btn-secondary btn-sm dropdown-toggle" data-toggle="dropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
<ul class="dropdown-menu dropdown-menu-right" style="min-width: 50px;">
<li><a id="rmd-show-all-code" href="#">Show All Code</a></li>
<li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li>
</ul>
</div>



<h1 class="title toc-ignore">hormone_final</h1>
<h4 class="date">2025-12-03</h4>

</div>


<p>###LH &amp; Estrogen Across Phases Topic: Examine average estrogen
and LH levels across menstrual cycle phases to see if hormonal patterns
match biological expectations</p>
<pre><code>## Warning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.
## ℹ Please use `linewidth` instead.
## This warning is displayed once every 8 hours.
## Call `lifecycle::last_lifecycle_warnings()` to see where this warning was
## generated.</code></pre>
<p><img src="hormone_final_files/figure-html/unnamed-chunk-3-1.png" width="672" />
EDA: Estrogen levels are highest in the Fertility (ovulatory) phase,
second highest in Luteal, and relatively low in Menstrual, gradually
rising from Follicular to Luteal. LH is much lower than estrogen
overall, peaking sharply in Fertility and remaining low in the other
phases.</p>
<p>Discussion: These patterns are consistent with established
physiology. The LH surge triggers ovulation during Fertility, while
estrogen gradually rises through Follicular phase, peaks in Fertility,
and remains moderate in Luteal. Menstrual phase shows low hormone
levels, reflecting the hormonal reset.</p>
<p>###Mood Swing Distribution Across Phases Topic: Assess whether
menstrual cycle phases influence mood swing intensity using violin
plots.</p>
<pre><code>## Warning: Removed 472 rows containing missing values or values outside the scale range
## (`geom_point()`).</code></pre>
<p><img src="hormone_final_files/figure-html/unnamed-chunk-4-1.png" width="672" />
EDA: Violin plots show substantial inter-individual variability.
Menstrual phase has the highest mood swing intensity (right-skewed
distribution, peak around 1.85), while Luteal phase shows lower values
with a wider base (more individuals with low mood swing).</p>
<p>Discussion: This distribution suggests that mood swings are most
severe during menstruation, likely due to the simultaneous withdrawal of
estrogen and progesterone. Luteal phase has moderate symptom expression,
consistent with premenstrual hormonal shifts.</p>
<p>Average Mood Swing Across Phases</p>
<p>Topic: Summarize average mood swing intensity across phases to
visualize general trends.
<img src="hormone_final_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<p>EDA: Average mood swing is highest in Menstrual phase (1.85), lowest
in Luteal phase (1.41), with intermediate levels in Follicular and
Fertility phases.</p>
<p>Discussion: These averages align with known biological mechanisms:
estrogen and progesterone withdrawal during menstruation contributes to
elevated mood instability. This confirms the phase-dependent pattern
suggested by the violin plot.</p>
<p>Mood Swing &amp; Fatigue Linear Mixed Models</p>
<p>Topic: Test whether mood swing and fatigue differ by menstrual phase,
accounting for repeated measures.</p>
<pre><code>## Linear mixed model fit by REML [&#39;lmerMod&#39;]
## Formula: moodswing_score ~ phase + (1 | id)
##    Data: hormone_symptoms
## REML criterion at convergence: 8006.314
## Random effects:
##  Groups   Name        Std.Dev.
##  id       (Intercept) 0.9781  
##  Residual             1.0035  
## Number of obs: 2751, groups:  id, 42
## Fixed Effects:
##     (Intercept)  phasefollicular      phaseluteal   phasemenstrual  
##         1.42765         -0.02442          0.10441          0.34466</code></pre>
<pre><code>## Linear mixed model fit by REML [&#39;lmerMod&#39;]
## Formula: fatigue_score ~ phase + (1 | id)
##    Data: hormone_symptoms
## REML criterion at convergence: 8847.962
## Random effects:
##  Groups   Name        Std.Dev.
##  id       (Intercept) 0.9068  
##  Residual             1.1735  
## Number of obs: 2751, groups:  id, 42
## Fixed Effects:
##     (Intercept)  phasefollicular      phaseluteal   phasemenstrual  
##         2.34636          0.02167          0.10965          0.30571</code></pre>
<p>EDA: Mood swings are lowest near ovulation, slightly higher in
Luteal, and peak during Menstrual phase. Fatigue shows a similar
pattern: lowest near ovulation, increasing through Luteal, highest
during Menstrual phase. Random effects indicate that some individuals
are chronically more fatigued or mood-sensitive than others, while
residual variance captures day-to-day variability.</p>
<p>Discussion: Linear mixed-effects models confirm phase-dependent
changes. Menstrual phase shows the greatest increases in both mood
swings and fatigue, consistent with estrogen and progesterone
withdrawal. Substantial inter-individual variability underscores the
importance of accounting for repeated measures.</p>
<p>###Flow Volume Distribution Across Phases</p>
<p>Topic: Visualize flow volume variation across phases with violin
plots to assess distribution patterns.
<img src="hormone_final_files/figure-html/unnamed-chunk-7-1.png" width="672" />
EDA: Luteal phase shows a right-skewed distribution, indicating most
low-flow observations but a few high-flow days. Menstrual phase is
narrow and tall, indicating consistently higher flow intensity.</p>
<p>Discussion: Flow volume is biologically highest during menstruation
due to active shedding of the endometrium. Luteal phase generally has
minimal flow, reflecting the quiescent secretory phase.</p>
<p>Average Flow Volume and Appetite Across Phases</p>
<p>Topic: Summarize average flow volume and appetite to observe general
trends across the menstrual cycle.
<img src="hormone_final_files/figure-html/unnamed-chunk-8-1.png" width="672" />
EDA: Menstrual phase has the highest average flow (2.38), Luteal is
lowest (0.03), Fertility is 0.07, and Follicular is 0.23.</p>
<p>Discussion: Average flow reflects physiological endometrial shedding.
Menstruation peaks in intensity, Luteal remains minimal, matching known
biological patterns.</p>
<p><img src="hormone_final_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<p>EDA: Appetite is highest in Fertility (2.96), lowest in Follicular
(2.85), Luteal 2.95, Menstrual 2.90.</p>
<p>Discussion: Appetite appears modestly correlated with estrogen
levels, peaking during Fertility when estrogen is highest. Other phases
show smaller differences, suggesting hormonal influence is
phase-specific but subtle.</p>
<p>###Linear Mixed Model: Appetite vs Estrogen Topic: Explore the
relationship between estrogen levels and appetite scores, accounting for
repeated measures.</p>
<pre><code>## Linear mixed model fit by REML [&#39;lmerMod&#39;]
## Formula: appetite_score ~ estrogen + (1 | id)
##    Data: hormone_symptoms
## 
## REML criterion at convergence: 6107.7
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -5.0464 -0.5701  0.0334  0.5181  3.9022 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev.
##  id       (Intercept) 0.1746   0.4178  
##  Residual             0.5223   0.7227  
## Number of obs: 2725, groups:  id, 42
## 
## Fixed effects:
##              Estimate Std. Error t value
## (Intercept) 2.8935583  0.0694275  41.677
## estrogen    0.0001294  0.0001489   0.869
## 
## Correlation of Fixed Effects:
##          (Intr)
## estrogen -0.291</code></pre>
<p>EDA: Random intercept variance (0.1746) indicates
participant-specific baseline appetite differences. The fixed effect of
estrogen is small (0.00013 per unit) and not significant (t =
0.869).</p>
<p>Discussion: After accounting for repeated measures, there is no clear
evidence that higher estrogen directly predicts higher appetite.
Baseline individual differences explain more variance than hormonal
fluctuations alone. Including phase or other hormones (LH, PDG) may
improve model sensitivity.</p>
<p>limitation:</p>
<p>Several limitations should be considered when interpreting these
findings. First, the dataset relies on self-reported symptom scores,
which may be subject to recall bias or subjective interpretation.
Second, while repeated measures are accounted for using linear mixed
models, the sample size for some phases may be limited, reducing
statistical power to detect subtle effects. Finally, other biological
and lifestyle factors—such as stress, sleep, diet, and physical
activity—were not controlled for, which could influence mood, appetite,
and fatigue. Therefore, the results should be interpreted as suggestive
of phase-related trends rather than definitive causal effects.</p>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->
<script>
$(document).ready(function () {
  window.initializeCodeFolding("show" === "show");
});
</script>

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
