<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Report</title>

<script src="site_libs/header-attrs-2.29/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/readable.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.13.2/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/navigation-1.1/codefolding.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/font-awesome-6.5.2/css/all.min.css" rel="stylesheet" />
<link href="site_libs/font-awesome-6.5.2/css/v4-shims.min.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->
<style type="text/css">
.code-folding-btn { margin-bottom: 4px; }
</style>



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html"></a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">
    <span class="fa fa-solid fa-spa"></span>
     
  </a>
</li>
<li>
  <a href="report.html">Report</a>
</li>
<li>
  <a href="data.html">Data</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Lifestyle Factors Analyses
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="hormone.html">Hormone &amp; Symptoms</a>
    </li>
    <li>
      <a href="sleep_stress_khue.html">Sleep &amp; Stress</a>
    </li>
    <li>
      <a href="exercise_hormone.html">Exercise</a>
    </li>
  </ul>
</li>
<li>
  <a href="p8105_final_project_proposal.html">Proposal</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="about.html">Meet the Team</a>
</li>
<li>
  <a>
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">

<div class="btn-group pull-right float-right">
<button type="button" class="btn btn-default btn-xs btn-secondary btn-sm dropdown-toggle" data-toggle="dropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
<ul class="dropdown-menu dropdown-menu-right" style="min-width: 50px;">
<li><a id="rmd-show-all-code" href="#">Show All Code</a></li>
<li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li>
</ul>
</div>



<h1 class="title toc-ignore">Report</h1>

</div>


<pre class="r"><code># Load packages 
library(tidyverse)
library(ggplot2)
library(modelr)
library(mgcv)
library(dplyr)
library(tidyr)
library(patchwork)
library(lme4)
library(lmerTest)
library(ggsci)

# Set plot theme
theme_set(theme_minimal() + theme(legend.position = &quot;bottom&quot;))
options(
  ggplot2.discrete.colour = function(...) scale_colour_brewer(..., palette = &quot;Pastel2&quot;),
  ggplot2.discrete.fill   = function(...) scale_fill_brewer(..., palette = &quot;Pastel2&quot;),

  ggplot2.continuous.colour = function(...) scale_colour_distiller(..., palette = &quot;PuRd&quot;),
  ggplot2.continuous.fill   = function(...) scale_fill_distiller(..., palette = &quot;PuRd&quot;)
)</code></pre>
<div id="motivation" class="section level1">
<h1>Motivation</h1>
<p>Half of the world’s population has experineced or will experience
menstruation; for many, this physiologic function occurs monthly for
several decades. For young adults who menstruate, symptoms and regular
menstration can be a vital health indicator. Abnormal symptoms can
further suggest reproductive tract abnormalities, such as uterine
fibroids or endometriosis. However, abnormal symptoms such as heavy
bleeding or extreme pain can also be attributed to lifestyle
characteristics. By leveraging a cohort of young adult menstruators, we
hope to better understand the relationship between physiological
menstrual characteristics and lifestyle factors such as stress, sleep,
and exercise. Understanding how day-to-day factors influence menstrual
health can help individuals who menstruate understand how to better
manage concerning symptoms or identify when abnormal symptoms could be
indicative of a more serious health concern.</p>
</div>
<div id="related-work" class="section level1">
<h1>Related Work</h1>
</div>
<div id="questions" class="section level1">
<h1>Questions</h1>
</div>
<div id="data" class="section level1">
<h1>Data</h1>
<p>We utilized the inclusive, multimodal, longitudinal, and
de-identified <a
href="https://physionet.org/content/mcphases/1.0.0/">mcPHASES</a>
(menstrual cycle Physiological, Hormonal, and Self-Reported Events and
Symptoms) dataset for menstrual health tracking with wearable
devices.</p>
<p>Data was collected from 42 menstruating young adults in Canada over
two 3-month intervals (one in 2022, and the other in 2024). Participants
wore Fitbit Sense smartwatches to measure physiological signals, and
Mira Plus Starter Kits to track their hormone levels. Participants also
self-reported daily symptom experiences like cramps, sleep quality, and
stress levels via a smartphone diary app.</p>
<p>The original dataset contains 23 structured tables organized by
signal category. For this project, we focused on the lifestyle factors
such as exercise, sleep, and stress, and menstrual cycle symptoms. The
datasets we used are the following:</p>
<ul>
<li>Demographics:
<ul>
<li><code>subject_info.csv</code>: static information such as age,
education, and age at menarche</li>
<li><code>height_and_weight.csv</code>: participant’s baselien height
and weight</li>
</ul></li>
<li>Hormone and Symptoms:
<ul>
<li><code>hormones_and_selfreport.csv</code>：self-reported daily data
including symptoms (e.g., cramps, mood, menstrual flow) and manually
entered hormone levels (LH, E3G, PdG)</li>
</ul></li>
<li>Lifestyle Factors:
<ul>
<li><code>stress_score.csv</code> [TODO]</li>
<li><code>sleep.csv</code>: sleep stages, time in bed</li>
<li><code>sleep_score.csv</code></li>
</ul></li>
</ul>
<hr />
<p>In total, we have 4 dataframes:</p>
<ol style="list-style-type: decimal">
<li><code>subject_info</code> (demographics data)</li>
<li><code>hormone_symptoms</code> (hormone and symtoms data)</li>
<li><code>sleep_stress</code> (sleep and stress related data)</li>
<li><code>exercise</code> (exercise related data).</li>
</ol>
<p>For different analyses, we merged the dataframes above by participant
<code>id</code> as needed.</p>
<hr />
<div id="subject_info---subject-relevant-data" class="section level3">
<h3><code>subject_info</code> - Subject-Relevant Data</h3>
<p>The <code>subject_info</code> dataframe contains participants
demographics data from <code>subject_info.csv</code> and
<code>height_and_weight.csv</code>, as well as participants study
enrollment year (this piece of information is from
<code>hormones_and_selfreport.csv</code>).</p>
<p>It contains a total of 62 observations of 19 variables. Some key
variables are the following:</p>
<ul>
<li><code>id</code>: participant’s unique identifier</li>
<li>Age relevant variables: <code>birth_year</code> and
<code>age_of_first_menarche</code></li>
<li>Height and weight related variables: <code>avg_height</code>,
<code>avg_weight</code>, <code>bmi</code></li>
<li>Study enrollment related information: <code>study</code> (flag of
which study the participant enrolled in, <code>1</code>=2022,
<code>2</code>=2024, <code>3</code>=both), <code>year</code> (the year
of study)</li>
<li>Categorical variables like <code>ethnicity</code>,
<code>education</code>,
<code>self_report_menstrual_health_literacy</code>, etc.</li>
</ul>
<pre class="r"><code>ht_wt = read_csv(&quot;data/height_and_weight.csv&quot;)|&gt; 
  janitor::clean_names() |&gt; 
  # calculate mean height/weight
  rowwise() |&gt;
  mutate(
    avg_height = mean(c(height_2022, height_2024), na.rm = TRUE),
    avg_weight = mean(c(weight_2022, weight_2024), na.rm = TRUE)
  ) |&gt;
  ungroup()</code></pre>
<pre class="r"><code># import csv file
hormones_and_selfreport = read_csv(&quot;data/hormones_and_selfreport.csv&quot;) |&gt; 
  janitor::clean_names() 
# extract study_flag
study_flag &lt;- hormones_and_selfreport  |&gt; 
  distinct(id, study_interval) |&gt; 
  mutate(flag = 1,
         study_interval = paste0(&quot;study_&quot;, study_interval)) |&gt; 
  pivot_wider(
    names_from = study_interval,
    values_from = flag,
    values_fill = 0  
  )</code></pre>
<pre class="r"><code># read in subject-info.csv
subject_info_raw = read_csv(&quot;data/subject-info.csv&quot;) |&gt; 
  janitor::clean_names()

subject_info &lt;- subject_info_raw  |&gt; 
  # merging
  left_join(ht_wt, by = &quot;id&quot;) |&gt; 
  left_join(study_flag, by = &quot;id&quot;) |&gt;
  # add a study_flag
  mutate(
    study = case_when(
      study_2022 == 1 &amp; study_2024 == 1 ~ 3L,  # both 2022 &amp; 2024
      study_2022 == 1 &amp; study_2024 == 0 ~ 1L,  
      study_2024 == 1 &amp; study_2022 == 0 ~ 2L,  
      TRUE ~ NA_integer_
    )
  ) |&gt; 
  # pivot_long for wt &amp; ht
  pivot_longer(
    cols = c(weight_2022, weight_2024, height_2022, height_2024),
    names_to  = c(&quot;.value&quot;, &quot;year&quot;), 
    names_sep = &quot;_&quot;                 
  ) |&gt; 
  rename(
    weight_yr = weight,
    height_yr = height
  ) |&gt; 
  # keep only the relevant study year
  filter(
    (study == 1 &amp; year == 2022) |
    (study == 2 &amp; year == 2024) |
    (study == 3)
  ) |&gt; 
  # calculate age
  mutate(
    year = as.numeric(year),
    birth_year = as.numeric(birth_year),
    age = year - birth_year
  ) |&gt; 
  # get a mean age for each id
  group_by(id) |&gt; 
  mutate(
    mean_age = mean(age, na.rm = TRUE)
  ) |&gt; 
  ungroup() |&gt; 
  # get BMI
  mutate(
    bmi = weight_yr / ( (height_yr / 100)^2 )
  )|&gt;
  # convert NaN to NA
  mutate(
    across(c(avg_weight, avg_height), 
           ~ if_else(is.nan(.), NA_real_, .))
  ) |&gt; 
  #this factors variables and also creates &quot;gender abrv&quot; and &quot;education abrv&quot;, which are simplified versions of these variables for cleaner tables and figures 
  mutate(
    education = str_trim(education),
    education_abrv = case_when(
      education == &quot;High school degree or equivalent (e.g. GED)&quot; ~ &quot;High School&quot;,
      education == &quot;Some university/ post-secondary, no degree&quot; ~ &quot;Some College&quot;,
      education == &quot;Bachelor&#39;s degree (e.g. BA, BS)&quot; ~ &quot;Bachelors&quot;,
      education %in% c(&quot;Master&#39;s degree (e.g. MA, MS, MEd)&quot;, &quot;Doctorate or professional degree&quot;) ~ &quot;Graduate Degree or Higher&quot;,
      TRUE ~ &quot;Other&quot;),
    education_abrv = factor(
      education_abrv,
      levels = c(&quot;High School&quot;, &quot;Some College&quot;, &quot;Bachelors&quot;, &quot;Graduate Degree or Higher&quot;, &quot;Other&quot;),
      ordered = TRUE),
     self_report_menstrual_health_literacy = factor(
      self_report_menstrual_health_literacy,
      levels = c(&quot;Non-existant&quot;, &quot;Low&quot;, &quot;Medium&quot;, &quot;High&quot;),
      ordered = TRUE),
    gender_abrv = case_when(
      gender %in% c(&quot;Gender Fluid&quot;, &quot;Non-binary&quot;) ~ &quot;Gender Fluid or Non-binary&quot;, 
      gender %in% c(&quot;Prefer not to say&quot;, &quot;Other&quot;) ~ &quot;Prefer not to say or Other&quot;, 
      gender == &quot;Woman&quot; ~ &quot;Woman&quot;),
      gender_abrv = factor(gender_abrv, levels = c(&quot;Woman&quot;, &quot;Gender Fluid or Non-binary&quot;, &quot;Prefer not to say or Other&quot;)), 
      sexually_active = factor(sexually_active, levels = c(&quot;Yes&quot;, &quot;No&quot;, &quot;Prefer not to say&quot;))) |&gt; 
  # only need 1 study_interval flag to indicate the study year
  mutate(study_interval = year) |&gt; 
  select(-study_2022, -study_2024, -year, -study) |&gt; 
  # rearrange the column order
  select(
    id,     
    study_interval,     
    everything()
  )</code></pre>
</div>
<div id="hormone_symptoms---hormone-self-reported-data"
class="section level3">
<h3><code>hormone_symptoms</code> - Hormone &amp; Self-reported
Data</h3>
<p>[TODO] add overview</p>
<pre class="r"><code># read in raw csv file
hormone_symptoms_raw &lt;- 
  read_csv(&quot;data/hormones_and_selfreport.csv&quot;) |&gt; 
  janitor::clean_names() 

# factor string values
likert_level_factor = c(&quot;not at all&quot;, &quot;very low/little&quot;, &quot;low&quot;, &quot;moderate&quot;, &quot;high&quot;, &quot;very high&quot;)
likert_levels_no_verylowlittle = c(&quot;not at all&quot;, &quot;very low&quot;, &quot;low&quot;, &quot;moderate&quot;, &quot;high&quot;, &quot;very high&quot;)
# likert_scale for numeric score conversion
likert_6_levels = c(&quot;not at all&quot; = 0, &quot;very low/little&quot; = 1, &quot;very low&quot; = 1, &quot;low&quot; = 2, &quot;moderate&quot; = 3, &quot;high&quot; = 4, &quot;very high&quot; = 5)


hormone_symptoms &lt;- hormone_symptoms_raw |&gt; 
  # convert all to lower case string for standardization
  mutate(across(flow_volume:bloating, 
                ~ ifelse(!is.na(.) &amp; !grepl(&quot;^\\d+$&quot;, .), tolower(.), .))) |&gt; 
  mutate(across(c(phase), ~ ifelse(!is.na(.) &amp; !grepl(&quot;^\\d+$&quot;, .), tolower(.), .))) |&gt; 
  # factor variables
  mutate(
    phase = factor(phase, levels = c(&quot;menstrual&quot;, &quot;follicular&quot;, &quot;fertility&quot;, &quot;luteal&quot;)),
    flow_volume = factor(flow_volume, 
                         levels = c(&quot;not at all&quot;, &quot;spotting / very light&quot;,&quot;light&quot;,&quot;moderate&quot;, &quot;somewhat heavy&quot;,&quot;heavy&quot;, &quot;very heavy&quot;)),
    flow_color = factor(flow_color,
                        levels = c(&quot;not at all&quot;, &quot;pink&quot;,&quot;bright red&quot;, &quot;dark brown / dark red&quot;, &quot;grey&quot;, &quot;black&quot;,&quot;other&quot;)),
  ) |&gt; 
  # factor character values
  mutate(
    across(
    .cols = c(sleepissue, headaches, stress, cramps, foodcravings, indigestion, bloating, moodswing, sorebreasts, fatigue),  
    .fns = ~ factor(., levels = likert_level_factor),  
    .names = &quot;{.col}&quot;  
  )
  ) |&gt; 
  mutate(across(
    .cols = c(appetite, exerciselevel),
    .fns = ~ factor(., levels = likert_levels_no_verylowlittle), 
    .names = &quot;{.col}&quot;  
  )) |&gt; 
  # convert categorical variable values to numeric intensity scores
  mutate(across(
    .cols = appetite:bloating,
    .fns = ~ recode(., !!!likert_6_levels),
    .names = &quot;{.col}_score&quot;
  )) |&gt; 
  # special conversion for flow
  mutate(
    flow_volume_score = case_when(
      flow_volume == &quot;not at all&quot; ~ 0,
      flow_volume == &quot;spotting / very light&quot; ~ 1,
      flow_volume == &quot;light&quot; ~ 2,
      flow_volume == &quot;moderate&quot; ~ 3,
      flow_volume == &quot;somewhat heavy&quot; ~ 4,
      flow_volume == &quot;heavy&quot; ~ 5,
      flow_volume == &quot;very heavy&quot; ~ 6,
      TRUE ~ NA_real_
    ),
    flow_color_score = case_when(
      flow_color == &quot;not at all&quot; ~ 0,
      flow_color == &quot;pink&quot; ~ 1,
      flow_color == &quot;bright red&quot; ~ 2,
      flow_color == &quot;dark brown / dark red&quot; ~ 3,
      flow_color == &quot;grey&quot; ~ 4,
      flow_color == &quot;black&quot; ~ 5,
      flow_color == &quot;other&quot; ~ 6,
      TRUE ~ NA_real_
    )
  )


#hormone_symptoms |&gt; 
#  filter(is.na(phase))</code></pre>
</div>
<div id="exercise" class="section level3">
<h3><code>exercise</code></h3>
</div>
<div id="sleep_stress" class="section level3">
<h3><code>sleep_stress</code></h3>
<p>[TODO] add overview</p>
<pre class="r"><code># load raw data from csv files
sleep_score_raw &lt;- read_csv(&quot;data/sleep_score.csv&quot;) |&gt;
  janitor::clean_names()
sleep_raw       &lt;- read_csv(&quot;data/sleep.csv&quot;) |&gt;
  janitor::clean_names()
stress_score_raw &lt;- read_csv(&quot;data/stress_score.csv&quot;) |&gt;
  janitor::clean_names()

# combine the sleep and stress score
sleep_score &lt;- sleep_score_raw |&gt;
  select(id,study_interval, day_in_study, overall_score, deep_sleep_in_minutes) |&gt; 
  mutate(sleep_score = overall_score) |&gt; 
  select(-overall_score) |&gt; 
  # remove duplicates by keeping the maximum score
  group_by(id, study_interval, day_in_study) |&gt; 
  slice_max(order_by = sleep_score, n = 1, with_ties = FALSE) |&gt; 
  ungroup()

stress_score &lt;- stress_score_raw |&gt;
  filter(calculation_failed == &quot;FALSE&quot;)|&gt;
  select(id, study_interval, day_in_study, stress_score)|&gt;
  distinct(id, study_interval, day_in_study, .keep_all = TRUE)


sleep_stress_score &lt;- full_join(sleep_score, stress_score, by=c(&quot;id&quot;, &quot;study_interval&quot;, &quot;day_in_study&quot;))

# check duplicates &gt;&gt; no duplicates nice
#sleep_stress_score %&gt;%
#  group_by(id, study_interval, day_in_study) %&gt;%
#  filter(n() &gt; 1)

# check of na values
#sum(is.na(sleep_stress$overall_score))
#sum(is.na(sleep_stress$stress_score))

# check how many days have both scores
#sleep_stress_score %&gt;%
#  filter(!is.na(stress_score) &amp; !is.na(sleep_score)) |&gt; 
#  nrow()</code></pre>
<pre class="r"><code># working on sleep data
sleep &lt;- sleep_raw|&gt;
  select(id,study_interval, sleep_end_day_in_study, timeinbed, mainsleep) |&gt;
  # changed to sleep_end_day
  mutate(day_in_study = sleep_end_day_in_study) |&gt;
  select(-sleep_end_day_in_study) |&gt; 
  # only keep main sleep = TRUE as mainsleep: boolean indicating whether this is the main sleep session of the day
  filter(
    mainsleep == TRUE
  ) |&gt; 
# check duplicates &gt;&gt; all duplicates from 2024
  group_by(id, study_interval, day_in_study) |&gt;
  summarise(
    timeinbed_mean = mean(timeinbed, na.rm = TRUE),
    mainsleep = first(mainsleep),
    .groups = &quot;drop&quot; 
  ) |&gt;
  ungroup() |&gt; 
  # no need flag
  select(-mainsleep)

# check duplicates
#sleep |&gt; 
 # filter(study_interval == 2022) |&gt; 
#  pull(timeinbed) |&gt; 
#  mean(na.rm = TRUE)
  
#sleep |&gt; count(id, study_interval, day_in_study) |&gt;
 # filter(n &gt; 1)

sleep_stress_daily &lt;- full_join(sleep, sleep_stress_score, by=c(&quot;id&quot;, &quot;study_interval&quot;, &quot;day_in_study&quot;))


#sleep %&gt;%
 # group_by(id, study_interval, day_in_study) %&gt;%
  #summarise(
   # total_timeinbed = sum(timeinbed, na.rm = TRUE),
    #.groups = &quot;drop&quot;  # 去除分组，返回一个没有分组的 data frame
#  ) |&gt; 
 # filter(total_timeinbed&gt;2000)
  
 # ggplot(aes(x = total_timeinbed)) +
#  geom_density(fill = &quot;skyblue&quot;, alpha = 0.5) +  # 填充颜色为淡蓝色，透明度为0.5
#  labs(title = &quot;Density Distribution of Total Time in Bed&quot;, 
 #      x = &quot;Total Time in Bed (hours)&quot;, 
  #     y = &quot;Density&quot;)</code></pre>
</div>
<div id="all_daily_data---merged-dataset" class="section level3">
<h3><code>all_daily_data</code> - Merged dataset</h3>
<p>We used <code>hormone_symptoms</code> as our anchor dataframe since
all of our outcome variables are from <code>hormone_symptoms</code>;
hence, we used <code>left_join</code> on it. In other words, if a person
did not have any hormone/symptoms related data on a given day, she would
not have any other types of data on that day (e.g. no
exercise/stress/sleep) in the merged dataset called
<code>all_daily_data</code>.</p>
<p>So now in this <code>all_daily_data</code>, each row represents a
daily data for a person in a specific study year (including sleep score,
stress score, daily exercise data, hormone and self-reported
symptoms).</p>
<p>First merged daily exercise data, then merged daily stress and sleep
data.</p>
<pre class="r"><code>all_daily_data &lt;- hormone_symptoms |&gt; 
  # MERGE exercise &amp; hormone
  left_join(exercise_daily, by = c(&quot;id&quot;, &quot;study_interval&quot;, &quot;day_in_study&quot;)) |&gt;
  # add flag exercised_flag for easy filtering in the future analyses
  # only need to keep exercised_flag==1 to have all rows with exercise data
  mutate(
    exercised_flag = ifelse(!is.na(n_sessions) &amp; n_sessions &gt; 0, 1, 0)
    # Replace NA with 0 for days without exercise ## NA might be not wearing the device instead of not exercising, I think it&#39;s better to remove them. Converting to 0 might cause very biased (right skewed) data/results
    #total_duration_min = replace_na(total_duration_min, 0),
    #total_active_min = replace_na(total_active_min, 0),
  ) |&gt; 
  # Remove individuals with no phase
  # filter(!is.na(phase))

  # MERGE sleep &amp; stress score data
  # noticed hormone_symptoms df has a stress_score column 
  # drop it
  select(-stress_score) |&gt; 
  left_join(sleep_stress_daily, by = c(&quot;id&quot;, &quot;study_interval&quot;, &quot;day_in_study&quot;)) |&gt; 
  # add flag sleep_stress_flag for easy filtering in the future analyses
  mutate(
    sleep_stress_flag = ifelse(
      !is.na(stress_score) &amp; !is.na(sleep_score),1,0
    )
  )  
  # MERGE demographic data
  # left_join(subject_info, by = c(&quot;id&quot;, &quot;study_interval&quot;)) </code></pre>
</div>
</div>
<div id="eda" class="section level1">
<h1>EDA</h1>
<p>-hormone</p>
<p>###LH &amp; Estrogen Across Phases Topic: Examine average estrogen
and LH levels across menstrual cycle phases to see if hormonal patterns
match biological expectations</p>
<pre><code>## Warning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.
## ℹ Please use `linewidth` instead.
## This warning is displayed once every 8 hours.
## Call `lifecycle::last_lifecycle_warnings()` to see where this warning was
## generated.</code></pre>
<p><img src="report_files/figure-html/unnamed-chunk-10-1.png" width="672" />
Estrogen levels are highest in the Fertility (ovulatory) phase, second
highest in Luteal, and relatively low in Menstrual, gradually rising
from Follicular to Luteal. LH is much lower than estrogen overall,
peaking sharply in Fertility and remaining low in the other phases.</p>
<p>###Mood Swing Distribution Across Phases Topic: Assess whether
menstrual cycle phases influence mood swing intensity using violin
plots.</p>
<pre><code>## Warning: Removed 462 rows containing missing values or values outside the scale range
## (`geom_point()`).</code></pre>
<p><img src="report_files/figure-html/unnamed-chunk-11-1.png" width="672" />
Violin plots show substantial inter-individual variability. Menstrual
phase has the highest mood swing intensity (right-skewed distribution,
peak around 1.85), while Luteal phase shows lower values with a wider
base (more individuals with low mood swing).</p>
<p>###Average Mood Swing Across Phases</p>
<p>Topic: Summarize average mood swing intensity across phases to
visualize general trends.
<img src="report_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
<p>Average mood swing is highest in Menstrual phase (1.85), lowest in
Luteal phase (1.41), with intermediate levels in Follicular and
Fertility phases.</p>
<p>###Mood Swing &amp; Fatigue Linear Mixed Models</p>
<p>Topic: Test whether mood swing and fatigue differ by menstrual phase,
accounting for repeated measures.</p>
<pre><code>## Linear mixed model fit by REML [&#39;lmerModLmerTest&#39;]
## Formula: moodswing_score ~ phase + (1 | id)
##    Data: hormone_symptoms
## REML criterion at convergence: 8006.314
## Random effects:
##  Groups   Name        Std.Dev.
##  id       (Intercept) 0.9781  
##  Residual             1.0035  
## Number of obs: 2751, groups:  id, 42
## Fixed Effects:
##     (Intercept)  phasefollicular      phaseluteal   phasemenstrual  
##         1.42765         -0.02442          0.10441          0.34466</code></pre>
<pre><code>## Linear mixed model fit by REML [&#39;lmerModLmerTest&#39;]
## Formula: fatigue_score ~ phase + (1 | id)
##    Data: hormone_symptoms
## REML criterion at convergence: 8847.962
## Random effects:
##  Groups   Name        Std.Dev.
##  id       (Intercept) 0.9068  
##  Residual             1.1735  
## Number of obs: 2751, groups:  id, 42
## Fixed Effects:
##     (Intercept)  phasefollicular      phaseluteal   phasemenstrual  
##         2.34636          0.02167          0.10965          0.30571</code></pre>
<p>Mood swings are lowest near ovulation, slightly higher in Luteal, and
peak during Menstrual phase. Fatigue shows a similar pattern: lowest
near ovulation, increasing through Luteal, highest during Menstrual
phase. Random effects indicate that some individuals are chronically
more fatigued or mood-sensitive than others, while residual variance
captures day-to-day variability.</p>
<p>###Flow Volume Distribution Across Phases</p>
<p>Topic: Visualize flow volume variation across phases with violin
plots to assess distribution patterns.
<img src="report_files/figure-html/unnamed-chunk-14-1.png" width="672" />
Luteal phase shows a right-skewed distribution, indicating most low-flow
observations but a few high-flow days. Menstrual phase is narrow and
tall, indicating consistently higher flow intensity.</p>
<p>Average Flow Volume and Appetite Across Phases</p>
<p>Topic: Summarize average flow volume and appetite to observe general
trends across the menstrual cycle.
<img src="report_files/figure-html/unnamed-chunk-15-1.png" width="672" />
Menstrual phase has the highest average flow (2.38), Luteal is lowest
(0.03), Fertility is 0.07, and Follicular is 0.23.</p>
<p><img src="report_files/figure-html/unnamed-chunk-16-1.png" width="672" />
Appetite is highest in Fertility (2.96), lowest in Follicular (2.85),
Luteal 2.95, Menstrual 2.90.</p>
<p>###Linear Mixed Model: Appetite vs Estrogen Topic: Explore the
relationship between estrogen levels and appetite scores, accounting for
repeated measures.</p>
<pre><code>## Linear mixed model fit by REML. t-tests use Satterthwaite&#39;s method [
## lmerModLmerTest]
## Formula: appetite_score ~ estrogen + (1 | id)
##    Data: hormone_symptoms
## 
## REML criterion at convergence: 6107.7
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -5.0464 -0.5701  0.0334  0.5181  3.9022 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev.
##  id       (Intercept) 0.1746   0.4178  
##  Residual             0.5223   0.7227  
## Number of obs: 2725, groups:  id, 42
## 
## Fixed effects:
##              Estimate Std. Error        df t value Pr(&gt;|t|)    
## (Intercept) 2.894e+00  6.943e-02 4.854e+01  41.677   &lt;2e-16 ***
## estrogen    1.294e-04  1.489e-04 2.721e+03   0.869    0.385    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Correlation of Fixed Effects:
##          (Intr)
## estrogen -0.291</code></pre>
<p>Random intercept variance (0.1746) indicates participant-specific
baseline appetite differences. The fixed effect of estrogen is small
(0.00013 per unit) and not significant (t = 0.869).</p>
</div>
<div id="modelling" class="section level1">
<h1>Modelling</h1>
</div>
<div id="discussion" class="section level1">
<h1>Discussion</h1>
<div id="data-handling" class="section level3">
<h3>Data Handling</h3>
<ul>
<li>data quality issues - take hormones &amp; self-reported as an
example</li>
</ul>
<p>regardless the most common missing data (due to self-report), 1)
integer values in categorical variables; 2) inconsistent likert scale
(‘very low/little’ vs. ‘very low’) &gt;&gt; give us the tip when we run
a study to collect different likert scale data, collect them at the same
scale for easy and consistent future data analyses.</p>
<ul>
<li>data entry issues - take sleep.csv as an example</li>
</ul>
</div>
<div id="limitation" class="section level2">
<h2>Limitation</h2>
</div>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->
<script>
$(document).ready(function () {
  window.initializeCodeFolding("hide" === "show");
});
</script>

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
